import type { Item } from '../types/grail';

export const runewords: Item[] = [
  {
    id: 'delirium',
    name: 'Delirium',
    link: 'https://d2runewizard.com/runewords/Delirium',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'dream',
    name: 'Dream',
    link: 'https://d2runewizard.com/runewords/Dream',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'flickeringflame',
    name: 'Flickering Flame',
    link: 'https://d2runewizard.com/runewords/Flickering%20Flame',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'lore',
    name: 'Lore',
    link: 'https://d2runewizard.com/runewords/Lore',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'nadir',
    name: 'Nadir',
    link: 'https://d2runewizard.com/runewords/Nadir',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'radiance',
    name: 'Radiance',
    link: 'https://d2runewizard.com/runewords/Radiance',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'wisdom',
    name: 'Wisdom',
    link: 'https://d2runewizard.com/runewords/Wisdom',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'bone',
    name: 'Bone',
    link: 'https://d2runewizard.com/runewords/Bone',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'bramble',
    name: 'Bramble',
    link: 'https://d2runewizard.com/runewords/Bramble',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'chainsofhonor',
    name: 'Chains of Honor',
    link: 'https://d2runewizard.com/runewords/Chains%20of%20Honor',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'dragon',
    name: 'Dragon',
    link: 'https://d2runewizard.com/runewords/Dragon',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'duress',
    name: 'Duress',
    link: 'https://d2runewizard.com/runewords/Duress',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'enigma',
    name: 'Enigma',
    link: 'https://d2runewizard.com/runewords/Enigma',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'enlightenment',
    name: 'Enlightenment',
    link: 'https://d2runewizard.com/runewords/Enlightenment',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'fortitude',
    name: 'Fortitude',
    link: 'https://d2runewizard.com/runewords/Fortitude',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'gloom',
    name: 'Gloom',
    link: 'https://d2runewizard.com/runewords/Gloom',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'lionheart',
    name: 'Lionheart',
    link: 'https://d2runewizard.com/runewords/Lionheart',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'myth',
    name: 'Myth',
    link: 'https://d2runewizard.com/runewords/Myth',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'peace',
    name: 'Peace',
    link: 'https://d2runewizard.com/runewords/Peace',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'principle',
    name: 'Principle',
    link: 'https://d2runewizard.com/runewords/Principle',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'prudence',
    name: 'Prudence',
    link: 'https://d2runewizard.com/runewords/Prudence',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'rain',
    name: 'Rain',
    link: 'https://d2runewizard.com/runewords/Rain',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'smoke',
    name: 'Smoke',
    link: 'https://d2runewizard.com/runewords/Smoke',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'stealth',
    name: 'Stealth',
    link: 'https://d2runewizard.com/runewords/Stealth',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'stone',
    name: 'Stone',
    link: 'https://d2runewizard.com/runewords/Stone',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'treachery',
    name: 'Treachery',
    link: 'https://d2runewizard.com/runewords/Treachery',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'wealth',
    name: 'Wealth',
    link: 'https://d2runewizard.com/runewords/Wealth',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'beast',
    name: 'Beast',
    link: 'https://d2runewizard.com/runewords/Beast',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'black',
    name: 'Black',
    link: 'https://d2runewizard.com/runewords/Black',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'brand',
    name: 'Brand',
    link: 'https://d2runewizard.com/runewords/Brand',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'breathofthedying',
    name: 'Breath of the Dying',
    link: 'https://d2runewizard.com/runewords/Breath%20of%20the%20Dying',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'calltoarms',
    name: 'Call to Arms',
    link: 'https://d2runewizard.com/runewords/Call%20to%20Arms',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'chaos',
    name: 'Chaos',
    link: 'https://d2runewizard.com/runewords/Chaos',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'crescentmoon-runeword',
    name: 'Crescent Moon',
    link: 'https://d2runewizard.com/runewords/Crescent%20Moon',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'death',
    name: 'Death',
    link: 'https://d2runewizard.com/runewords/Death',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'destruction',
    name: 'Destruction',
    link: 'https://d2runewizard.com/runewords/Destruction',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'doom',
    name: 'Doom',
    link: 'https://d2runewizard.com/runewords/Doom',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'edge',
    name: 'Edge',
    link: 'https://d2runewizard.com/runewords/Edge',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'eternity',
    name: 'Eternity',
    link: 'https://d2runewizard.com/runewords/Eternity',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'faith',
    name: 'Faith',
    link: 'https://d2runewizard.com/runewords/Faith',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'famine',
    name: 'Famine',
    link: 'https://d2runewizard.com/runewords/Famine',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'fury',
    name: 'Fury',
    link: 'https://d2runewizard.com/runewords/Fury',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'grief',
    name: 'Grief',
    link: 'https://d2runewizard.com/runewords/Grief',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'handofjustice',
    name: 'Hand of Justice',
    link: 'https://d2runewizard.com/runewords/Hand%20of%20Justice',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'harmony',
    name: 'Harmony',
    link: 'https://d2runewizard.com/runewords/Harmony',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'heartoftheoak',
    name: 'Heart of the Oak',
    link: 'https://d2runewizard.com/runewords/Heart%20of%20the%20Oak',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'holythunder',
    name: 'Holy Thunder',
    link: 'https://d2runewizard.com/runewords/Holy%20Thunder',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'honor',
    name: 'Honor',
    link: 'https://d2runewizard.com/runewords/Honor',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'ice',
    name: 'Ice',
    link: 'https://d2runewizard.com/runewords/Ice',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'infinity',
    name: 'Infinity',
    link: 'https://d2runewizard.com/runewords/Infinity',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'insight',
    name: 'Insight',
    link: 'https://d2runewizard.com/runewords/Insight',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'kingsgrace',
    name: "King's Grace",
    link: "https://d2runewizard.com/runewords/King's%20Grace",
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'kingslayer',
    name: 'Kingslayer',
    link: 'https://d2runewizard.com/runewords/Kingslayer',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'lastwish',
    name: 'Last Wish',
    link: 'https://d2runewizard.com/runewords/Last%20Wish',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'lawbringer',
    name: 'Lawbringer',
    link: 'https://d2runewizard.com/runewords/Lawbringer',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'leaf',
    name: 'Leaf',
    link: 'https://d2runewizard.com/runewords/Leaf',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'malice',
    name: 'Malice',
    link: 'https://d2runewizard.com/runewords/Malice',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'melody',
    name: 'Melody',
    link: 'https://d2runewizard.com/runewords/Melody',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'memory',
    name: 'Memory',
    link: 'https://d2runewizard.com/runewords/Memory',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'mist',
    name: 'Mist',
    link: 'https://d2runewizard.com/runewords/Mist',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'oath',
    name: 'Oath',
    link: 'https://d2runewizard.com/runewords/Oath',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'obedience',
    name: 'Obedience',
    link: 'https://d2runewizard.com/runewords/Obedience',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'obsession',
    name: 'Obsession',
    link: 'https://d2runewizard.com/runewords/Obsession',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'passion',
    name: 'Passion',
    link: 'https://d2runewizard.com/runewords/Passion',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'pattern',
    name: 'Pattern',
    link: 'https://d2runewizard.com/runewords/Pattern',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    link: 'https://d2runewizard.com/runewords/Phoenix',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'plague',
    name: 'Plague',
    link: 'https://d2runewizard.com/runewords/Plague',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'pride',
    name: 'Pride',
    link: 'https://d2runewizard.com/runewords/Pride',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'rift',
    name: 'Rift',
    link: 'https://d2runewizard.com/runewords/Rift',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'silence',
    name: 'Silence',
    link: 'https://d2runewizard.com/runewords/Silence',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'spirit',
    name: 'Spirit',
    link: 'https://d2runewizard.com/runewords/Spirit',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'steel',
    name: 'Steel',
    link: 'https://d2runewizard.com/runewords/Steel',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'strength',
    name: 'Strength',
    link: 'https://d2runewizard.com/runewords/Strength',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'unbendingwill',
    name: 'Unbending Will',
    link: 'https://d2runewizard.com/runewords/Unbending%20Will',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'venom',
    name: 'Venom',
    link: 'https://d2runewizard.com/runewords/Venom',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'voiceofreason',
    name: 'Voice of Reason',
    link: 'https://d2runewizard.com/runewords/Voice%20of%20Reason',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'white',
    name: 'White',
    link: 'https://d2runewizard.com/runewords/White',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'wind',
    name: 'Wind',
    link: 'https://d2runewizard.com/runewords/Wind',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'wrath',
    name: 'Wrath',
    link: 'https://d2runewizard.com/runewords/Wrath',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'zephyr',
    name: 'Zephyr',
    link: 'https://d2runewizard.com/runewords/Zephyr',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'ancientspledge',
    name: "Ancient's Pledge",
    link: "https://d2runewizard.com/runewords/Ancient's%20Pledge",
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'exile',
    name: 'Exile',
    link: 'https://d2runewizard.com/runewords/Exile',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'rhyme',
    name: 'Rhyme',
    link: 'https://d2runewizard.com/runewords/Rhyme',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    link: 'https://d2runewizard.com/runewords/Sanctuary',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'splendor',
    name: 'Splendor',
    link: 'https://d2runewizard.com/runewords/Splendor',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    link: 'https://d2runewizard.com/runewords/Bulwark',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'cure',
    name: 'Cure',
    link: 'https://d2runewizard.com/runewords/Cure',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'ground',
    name: 'Ground',
    link: 'https://d2runewizard.com/runewords/Ground',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'hearth',
    name: 'Hearth',
    link: 'https://d2runewizard.com/runewords/Hearth',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'temper',
    name: 'Temper',
    link: 'https://d2runewizard.com/runewords/Temper',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'hustle',
    name: 'Hustle',
    link: 'https://d2runewizard.com/runewords/Hustle',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'mosaic',
    name: 'Mosaic',
    link: 'https://d2runewizard.com/runewords/Mosaic',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
  {
    id: 'metamorphosis',
    name: 'Metamorphosis',
    link: 'https://d2runewizard.com/runewords/Metamorphosis',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
  },
];
