import type { Item } from '../types/grail';

export const runes: Item[] = [
  {
    id: 'el',
    code: 'r01',
    name: 'El',
    link: 'https://d2runewizard.com/runes/El',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'eld',
    code: 'r02',
    name: 'Eld',
    link: 'https://d2runewizard.com/runes/Eld',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'tir',
    code: 'r03',
    name: 'Tir',
    link: 'https://d2runewizard.com/runes/Tir',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'nef',
    code: 'r04',
    name: 'Nef',
    link: 'https://d2runewizard.com/runes/Nef',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'eth',
    code: 'r05',
    name: 'Eth',
    link: 'https://d2runewizard.com/runes/Eth',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ith',
    code: 'r06',
    name: 'Ith',
    link: 'https://d2runewizard.com/runes/Ith',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'tal',
    code: 'r07',
    name: 'Tal',
    link: 'https://d2runewizard.com/runes/Tal',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ral',
    code: 'r08',
    name: 'Ral',
    link: 'https://d2runewizard.com/runes/Ral',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ort',
    code: 'r09',
    name: 'Ort',
    link: 'https://d2runewizard.com/runes/Ort',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'thul',
    code: 'r10',
    name: 'Thul',
    link: 'https://d2runewizard.com/runes/Thul',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'amn',
    code: 'r11',
    name: 'Amn',
    link: 'https://d2runewizard.com/runes/Amn',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'sol',
    code: 'r12',
    name: 'Sol',
    link: 'https://d2runewizard.com/runes/Sol',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'shael',
    code: 'r13',
    name: 'Shael',
    link: 'https://d2runewizard.com/runes/Shael',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'dol',
    code: 'r14',
    name: 'Dol',
    link: 'https://d2runewizard.com/runes/Dol',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'hel',
    code: 'r15',
    name: 'Hel',
    link: 'https://d2runewizard.com/runes/Hel',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'io',
    code: 'r16',
    name: 'Io',
    link: 'https://d2runewizard.com/runes/Io',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'lum',
    code: 'r17',
    name: 'Lum',
    link: 'https://d2runewizard.com/runes/Lum',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ko',
    code: 'r18',
    name: 'Ko',
    link: 'https://d2runewizard.com/runes/Ko',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'fal',
    code: 'r19',
    name: 'Fal',
    link: 'https://d2runewizard.com/runes/Fal',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'lem',
    code: 'r20',
    name: 'Lem',
    link: 'https://d2runewizard.com/runes/Lem',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'pul',
    code: 'r21',
    name: 'Pul',
    link: 'https://d2runewizard.com/runes/Pul',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'um',
    code: 'r22',
    name: 'Um',
    link: 'https://d2runewizard.com/runes/Um',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'mal',
    code: 'r23',
    name: 'Mal',
    link: 'https://d2runewizard.com/runes/Mal',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ist',
    code: 'r24',
    name: 'Ist',
    link: 'https://d2runewizard.com/runes/Ist',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'gul',
    code: 'r25',
    name: 'Gul',
    link: 'https://d2runewizard.com/runes/Gul',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'vex',
    code: 'r26',
    name: 'Vex',
    link: 'https://d2runewizard.com/runes/Vex',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ohm',
    code: 'r27',
    name: 'Ohm',
    link: 'https://d2runewizard.com/runes/Ohm',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'lo',
    code: 'r28',
    name: 'Lo',
    link: 'https://d2runewizard.com/runes/Lo',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'sur',
    code: 'r29',
    name: 'Sur',
    link: 'https://d2runewizard.com/runes/Sur',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ber',
    code: 'r30',
    name: 'Ber',
    link: 'https://d2runewizard.com/runes/Ber',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'jah',
    code: 'r31',
    name: 'Jah',
    link: 'https://d2runewizard.com/runes/Jah',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'cham',
    code: 'r32',
    name: 'Cham',
    link: 'https://d2runewizard.com/runes/Cham',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'zod',
    code: 'r33',
    name: 'Zod',
    link: 'https://d2runewizard.com/runes/Zod',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
];
