import type { Item } from '../types/grail';

export const runewords: Item[] = [
  {
    id: 'delirium',
    name: 'Delirium',
    link: 'https://d2runewizard.com/runewords/Delirium',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['lem', 'ist', 'io'],
  },
  {
    id: 'dream',
    name: 'Dream',
    link: 'https://d2runewizard.com/runewords/Dream',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['io', 'jah', 'pul'],
  },
  {
    id: 'flickeringflame',
    name: 'Flickering Flame',
    link: 'https://d2runewizard.com/runewords/Flickering%20Flame',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['nef', 'pul', 'vex'],
  },
  {
    id: 'lore',
    name: 'Lore',
    link: 'https://d2runewizard.com/runewords/Lore',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ort', 'sol'],
  },
  {
    id: 'nadir',
    name: 'Nadir',
    link: 'https://d2runewizard.com/runewords/Nadir',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['nef', 'tir'],
  },
  {
    id: 'radiance',
    name: 'Radiance',
    link: 'https://d2runewizard.com/runewords/Radiance',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['nef', 'sol', 'ith'],
  },
  {
    id: 'wisdom',
    name: 'Wisdom',
    link: 'https://d2runewizard.com/runewords/Wisdom',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['pul', 'ith', 'eld'],
  },
  {
    id: 'bone',
    name: 'Bone',
    link: 'https://d2runewizard.com/runewords/Bone',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['sol', 'um', 'um'],
  },
  {
    id: 'bramble',
    name: 'Bramble',
    link: 'https://d2runewizard.com/runewords/Bramble',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ral', 'ohm', 'sur', 'eth'],
  },
  {
    id: 'chainsofhonor',
    name: 'Chains of Honor',
    link: 'https://d2runewizard.com/runewords/Chains%20of%20Honor',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['dol', 'um', 'ber', 'ist'],
  },
  {
    id: 'dragon',
    name: 'Dragon',
    link: 'https://d2runewizard.com/runewords/Dragon',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['sur', 'lo', 'sol'],
  },
  {
    id: 'duress',
    name: 'Duress',
    link: 'https://d2runewizard.com/runewords/Duress',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'um', 'thul'],
  },
  {
    id: 'enigma',
    name: 'Enigma',
    link: 'https://d2runewizard.com/runewords/Enigma',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['jah', 'ith', 'ber'],
  },
  {
    id: 'enlightenment',
    name: 'Enlightenment',
    link: 'https://d2runewizard.com/runewords/Enlightenment',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['pul', 'ral', 'sol'],
  },
  {
    id: 'fortitude',
    name: 'Fortitude',
    link: 'https://d2runewizard.com/runewords/Fortitude',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['el', 'sol', 'dol', 'lo'],
  },
  {
    id: 'gloom',
    name: 'Gloom',
    link: 'https://d2runewizard.com/runewords/Gloom',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['fal', 'um', 'pul'],
  },
  {
    id: 'lionheart',
    name: 'Lionheart',
    link: 'https://d2runewizard.com/runewords/Lionheart',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['hel', 'lum', 'fal'],
  },
  {
    id: 'myth',
    name: 'Myth',
    link: 'https://d2runewizard.com/runewords/Myth',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['hel', 'amn', 'nef'],
  },
  {
    id: 'peace',
    name: 'Peace',
    link: 'https://d2runewizard.com/runewords/Peace',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'thul', 'amn'],
  },
  {
    id: 'principle',
    name: 'Principle',
    link: 'https://d2runewizard.com/runewords/Principle',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ral', 'gul', 'eld'],
  },
  {
    id: 'prudence',
    name: 'Prudence',
    link: 'https://d2runewizard.com/runewords/Prudence',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['mal', 'tir'],
  },
  {
    id: 'rain',
    name: 'Rain',
    link: 'https://d2runewizard.com/runewords/Rain',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ort', 'mal', 'ith'],
  },
  {
    id: 'smoke',
    name: 'Smoke',
    link: 'https://d2runewizard.com/runewords/Smoke',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['nef', 'lum'],
  },
  {
    id: 'stealth',
    name: 'Stealth',
    link: 'https://d2runewizard.com/runewords/Stealth',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['tal', 'eth'],
  },
  {
    id: 'stone',
    name: 'Stone',
    link: 'https://d2runewizard.com/runewords/Stone',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'um', 'pul', 'lum'],
  },
  {
    id: 'treachery',
    name: 'Treachery',
    link: 'https://d2runewizard.com/runewords/Treachery',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'thul', 'lem'],
  },
  {
    id: 'wealth',
    name: 'Wealth',
    link: 'https://d2runewizard.com/runewords/Wealth',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['lem', 'ko', 'tir'],
  },
  {
    id: 'beast',
    name: 'Beast',
    link: 'https://d2runewizard.com/runewords/Beast',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ber', 'tir', 'um', 'mal', 'lum'],
  },
  {
    id: 'black',
    name: 'Black',
    link: 'https://d2runewizard.com/runewords/Black',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['thul', 'io', 'nef'],
  },
  {
    id: 'brand',
    name: 'Brand',
    link: 'https://d2runewizard.com/runewords/Brand',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['jah', 'lo', 'mal', 'gul'],
  },
  {
    id: 'breathofthedying',
    name: 'Breath of the Dying',
    link: 'https://d2runewizard.com/runewords/Breath%20of%20the%20Dying',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['vex', 'hel', 'el', 'eld', 'zod', 'eth'],
  },
  {
    id: 'calltoarms',
    name: 'Call to Arms',
    link: 'https://d2runewizard.com/runewords/Call%20to%20Arms',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['amn', 'ral', 'mal', 'ist', 'ohm'],
  },
  {
    id: 'chaos',
    name: 'Chaos',
    link: 'https://d2runewizard.com/runewords/Chaos',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['fal', 'ohm', 'um'],
  },
  {
    id: 'crescentmoon-runeword',
    name: 'Crescent Moon',
    link: 'https://d2runewizard.com/runewords/Crescent%20Moon',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'um', 'tir'],
  },
  {
    id: 'death',
    name: 'Death',
    link: 'https://d2runewizard.com/runewords/Death',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['hel', 'el', 'vex', 'ort', 'gul'],
  },
  {
    id: 'destruction',
    name: 'Destruction',
    link: 'https://d2runewizard.com/runewords/Destruction',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['vex', 'lo', 'ber', 'jah', 'ko'],
  },
  {
    id: 'doom',
    name: 'Doom',
    link: 'https://d2runewizard.com/runewords/Doom',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['hel', 'ohm', 'um', 'lo', 'cham'],
  },
  {
    id: 'edge',
    name: 'Edge',
    link: 'https://d2runewizard.com/runewords/Edge',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['tir', 'tal', 'amn'],
  },
  {
    id: 'eternity',
    name: 'Eternity',
    link: 'https://d2runewizard.com/runewords/Eternity',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['amn', 'ber', 'ist', 'sol', 'sur'],
  },
  {
    id: 'faith',
    name: 'Faith',
    link: 'https://d2runewizard.com/runewords/Faith',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ohm', 'jah', 'lem', 'eld'],
  },
  {
    id: 'famine',
    name: 'Famine',
    link: 'https://d2runewizard.com/runewords/Famine',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['fal', 'ohm', 'ort', 'jah'],
  },
  {
    id: 'fury',
    name: 'Fury',
    link: 'https://d2runewizard.com/runewords/Fury',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['jah', 'gul', 'eth'],
  },
  {
    id: 'grief',
    name: 'Grief',
    link: 'https://d2runewizard.com/runewords/Grief',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['eth', 'tir', 'lo', 'mal', 'ral'],
  },
  {
    id: 'handofjustice',
    name: 'Hand of Justice',
    link: 'https://d2runewizard.com/runewords/Hand%20of%20Justice',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['sur', 'cham', 'amn', 'lo'],
  },
  {
    id: 'harmony',
    name: 'Harmony',
    link: 'https://d2runewizard.com/runewords/Harmony',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['tir', 'ith', 'sol', 'ko'],
  },
  {
    id: 'heartoftheoak',
    name: 'Heart of the Oak',
    link: 'https://d2runewizard.com/runewords/Heart%20of%20the%20Oak',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ko', 'vex', 'pul', 'thul'],
  },
  {
    id: 'holythunder',
    name: 'Holy Thunder',
    link: 'https://d2runewizard.com/runewords/Holy%20Thunder',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['eth', 'ral', 'ort', 'tal'],
  },
  {
    id: 'honor',
    name: 'Honor',
    link: 'https://d2runewizard.com/runewords/Honor',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['amn', 'el', 'ith', 'tir', 'sol'],
  },
  {
    id: 'ice',
    name: 'Ice',
    link: 'https://d2runewizard.com/runewords/Ice',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['amn', 'shael', 'jah', 'lo'],
  },
  {
    id: 'infinity',
    name: 'Infinity',
    link: 'https://d2runewizard.com/runewords/Infinity',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ber', 'mal', 'ber', 'ist'],
  },
  {
    id: 'insight',
    name: 'Insight',
    link: 'https://d2runewizard.com/runewords/Insight',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ral', 'tir', 'tal', 'sol'],
  },
  {
    id: 'kingsgrace',
    name: "King's Grace",
    link: "https://d2runewizard.com/runewords/King's%20Grace",
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['amn', 'ral', 'thul'],
  },
  {
    id: 'kingslayer',
    name: 'Kingslayer',
    link: 'https://d2runewizard.com/runewords/Kingslayer',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['mal', 'um', 'gul', 'fal'],
  },
  {
    id: 'lastwish',
    name: 'Last Wish',
    link: 'https://d2runewizard.com/runewords/Last%20Wish',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['jah', 'mal', 'jah', 'sur', 'jah', 'ber'],
  },
  {
    id: 'lawbringer',
    name: 'Lawbringer',
    link: 'https://d2runewizard.com/runewords/Lawbringer',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['amn', 'lem', 'ko'],
  },
  {
    id: 'leaf',
    name: 'Leaf',
    link: 'https://d2runewizard.com/runewords/Leaf',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['tir', 'ral'],
  },
  {
    id: 'malice',
    name: 'Malice',
    link: 'https://d2runewizard.com/runewords/Malice',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ith', 'el', 'eth'],
  },
  {
    id: 'melody',
    name: 'Melody',
    link: 'https://d2runewizard.com/runewords/Melody',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'ko', 'nef'],
  },
  {
    id: 'memory',
    name: 'Memory',
    link: 'https://d2runewizard.com/runewords/Memory',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['lum', 'io', 'sol', 'eth'],
  },
  {
    id: 'mist',
    name: 'Mist',
    link: 'https://d2runewizard.com/runewords/Mist',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['cham', 'shael', 'gul', 'thul', 'ith'],
  },
  {
    id: 'oath',
    name: 'Oath',
    link: 'https://d2runewizard.com/runewords/Oath',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'pul', 'mal', 'lum'],
  },
  {
    id: 'obedience',
    name: 'Obedience',
    link: 'https://d2runewizard.com/runewords/Obedience',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['hel', 'ko', 'thul', 'eth', 'fal'],
  },
  {
    id: 'obsession',
    name: 'Obsession',
    link: 'https://d2runewizard.com/runewords/Obsession',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['zod', 'ist', 'lem', 'lum', 'io', 'nef'],
  },
  {
    id: 'passion',
    name: 'Passion',
    link: 'https://d2runewizard.com/runewords/Passion',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['dol', 'ort', 'eld', 'lem'],
  },
  {
    id: 'pattern',
    name: 'Pattern',
    link: 'https://d2runewizard.com/runewords/Pattern',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['tal', 'ort', 'thul'],
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    link: 'https://d2runewizard.com/runewords/Phoenix',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['vex', 'vex', 'lo', 'jah'],
  },
  {
    id: 'plague',
    name: 'Plague',
    link: 'https://d2runewizard.com/runewords/Plague',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['cham', 'shael', 'um'],
  },
  {
    id: 'pride',
    name: 'Pride',
    link: 'https://d2runewizard.com/runewords/Pride',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['cham', 'sur', 'io', 'lo'],
  },
  {
    id: 'rift',
    name: 'Rift',
    link: 'https://d2runewizard.com/runewords/Rift',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['hel', 'ko', 'lem', 'gul'],
  },
  {
    id: 'silence',
    name: 'Silence',
    link: 'https://d2runewizard.com/runewords/Silence',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['dol', 'eld', 'hel', 'ist', 'tir', 'vex'],
  },
  {
    id: 'spirit',
    name: 'Spirit',
    link: 'https://d2runewizard.com/runewords/Spirit',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['tal', 'thul', 'ort', 'amn'],
  },
  {
    id: 'steel',
    name: 'Steel',
    link: 'https://d2runewizard.com/runewords/Steel',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['tir', 'el'],
  },
  {
    id: 'strength',
    name: 'Strength',
    link: 'https://d2runewizard.com/runewords/Strength',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['amn', 'tir'],
  },
  {
    id: 'unbendingwill',
    name: 'Unbending Will',
    link: 'https://d2runewizard.com/runewords/Unbending%20Will',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['fal', 'io', 'ith', 'eld', 'el', 'hel'],
  },
  {
    id: 'venom',
    name: 'Venom',
    link: 'https://d2runewizard.com/runewords/Venom',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['tal', 'dol', 'mal'],
  },
  {
    id: 'voiceofreason',
    name: 'Voice of Reason',
    link: 'https://d2runewizard.com/runewords/Voice%20of%20Reason',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['lem', 'ko', 'el', 'eld'],
  },
  {
    id: 'white',
    name: 'White',
    link: 'https://d2runewizard.com/runewords/White',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['dol', 'io'],
  },
  {
    id: 'wind',
    name: 'Wind',
    link: 'https://d2runewizard.com/runewords/Wind',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['sur', 'el'],
  },
  {
    id: 'wrath',
    name: 'Wrath',
    link: 'https://d2runewizard.com/runewords/Wrath',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['pul', 'lum', 'ber', 'mal'],
  },
  {
    id: 'zephyr',
    name: 'Zephyr',
    link: 'https://d2runewizard.com/runewords/Zephyr',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ort', 'eth'],
  },
  {
    id: 'ancientspledge',
    name: "Ancient's Pledge",
    link: "https://d2runewizard.com/runewords/Ancient's%20Pledge",
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ral', 'ort', 'tal'],
  },
  {
    id: 'exile',
    name: 'Exile',
    link: 'https://d2runewizard.com/runewords/Exile',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['vex', 'ohm', 'ist', 'dol'],
  },
  {
    id: 'rhyme',
    name: 'Rhyme',
    link: 'https://d2runewizard.com/runewords/Rhyme',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'eth'],
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    link: 'https://d2runewizard.com/runewords/Sanctuary',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['ko', 'ko', 'mal'],
  },
  {
    id: 'splendor',
    name: 'Splendor',
    link: 'https://d2runewizard.com/runewords/Splendor',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['eth', 'lum'],
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    link: 'https://d2runewizard.com/runewords/Bulwark',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'io', 'sol'],
  },
  {
    id: 'cure',
    name: 'Cure',
    link: 'https://d2runewizard.com/runewords/Cure',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'io', 'tal'],
  },
  {
    id: 'ground',
    name: 'Ground',
    link: 'https://d2runewizard.com/runewords/Ground',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'io', 'ort'],
  },
  {
    id: 'hearth',
    name: 'Hearth',
    link: 'https://d2runewizard.com/runewords/Hearth',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'io', 'thul'],
  },
  {
    id: 'temper',
    name: 'Temper',
    link: 'https://d2runewizard.com/runewords/Temper',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'io', 'ral'],
  },
  {
    id: 'hustle',
    name: 'Hustle',
    link: 'https://d2runewizard.com/runewords/Hustle',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['shael', 'ko', 'eld'],
  },
  {
    id: 'mosaic',
    name: 'Mosaic',
    link: 'https://d2runewizard.com/runewords/Mosaic',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['mal', 'gul', 'amn'],
  },
  {
    id: 'metamorphosis',
    name: 'Metamorphosis',
    link: 'https://d2runewizard.com/runewords/Metamorphosis',
    etherealType: 'none',
    type: 'runeword',
    category: 'runewords',
    subCategory: 'runewords',
    treasureClass: 'normal',
    runes: ['io', 'cham', 'fal'],
  },
];
