import type { Item } from '../types/grail';

export const runes: Item[] = [
  {
    id: 'el',
    code: 'r01',
    itemBase: 'El Rune',
    imageFilename: 'el_rune.png',
    name: 'El',
    link: 'https://d2runewizard.com/runes/El',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'eld',
    code: 'r02',
    itemBase: 'Eld Rune',
    imageFilename: 'eld_rune.png',
    name: 'Eld',
    link: 'https://d2runewizard.com/runes/Eld',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'tir',
    code: 'r03',
    itemBase: 'Tir Rune',
    imageFilename: 'tir_rune.png',
    name: 'Tir',
    link: 'https://d2runewizard.com/runes/Tir',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'nef',
    code: 'r04',
    itemBase: 'Nef Rune',
    imageFilename: 'nef_rune.png',
    name: 'Nef',
    link: 'https://d2runewizard.com/runes/Nef',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'eth',
    code: 'r05',
    itemBase: 'Eth Rune',
    imageFilename: 'eth_rune.png',
    name: 'Eth',
    link: 'https://d2runewizard.com/runes/Eth',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ith',
    code: 'r06',
    itemBase: 'Ith Rune',
    imageFilename: 'ith_rune.png',
    name: 'Ith',
    link: 'https://d2runewizard.com/runes/Ith',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'tal',
    code: 'r07',
    itemBase: 'Tal Rune',
    imageFilename: 'tal_rune.png',
    name: 'Tal',
    link: 'https://d2runewizard.com/runes/Tal',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ral',
    code: 'r08',
    itemBase: 'Ral Rune',
    imageFilename: 'ral_rune.png',
    name: 'Ral',
    link: 'https://d2runewizard.com/runes/Ral',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ort',
    code: 'r09',
    itemBase: 'Ort Rune',
    imageFilename: 'ort_rune.png',
    name: 'Ort',
    link: 'https://d2runewizard.com/runes/Ort',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'thul',
    code: 'r10',
    itemBase: 'Thul Rune',
    imageFilename: 'thul_rune.png',
    name: 'Thul',
    link: 'https://d2runewizard.com/runes/Thul',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'amn',
    code: 'r11',
    itemBase: 'Amn Rune',
    imageFilename: 'amn_rune.png',
    name: 'Amn',
    link: 'https://d2runewizard.com/runes/Amn',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'sol',
    code: 'r12',
    itemBase: 'Sol Rune',
    imageFilename: 'sol_rune.png',
    name: 'Sol',
    link: 'https://d2runewizard.com/runes/Sol',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'shael',
    code: 'r13',
    itemBase: 'Shael Rune',
    imageFilename: 'shael_rune.png',
    name: 'Shael',
    link: 'https://d2runewizard.com/runes/Shael',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'dol',
    code: 'r14',
    itemBase: 'Dol Rune',
    imageFilename: 'dol_rune.png',
    name: 'Dol',
    link: 'https://d2runewizard.com/runes/Dol',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'hel',
    code: 'r15',
    itemBase: 'Hel Rune',
    imageFilename: 'hel_rune.png',
    name: 'Hel',
    link: 'https://d2runewizard.com/runes/Hel',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'io',
    code: 'r16',
    itemBase: 'Io Rune',
    imageFilename: 'io_rune.png',
    name: 'Io',
    link: 'https://d2runewizard.com/runes/Io',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'lum',
    code: 'r17',
    itemBase: 'Lum Rune',
    imageFilename: 'lum_rune.png',
    name: 'Lum',
    link: 'https://d2runewizard.com/runes/Lum',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ko',
    code: 'r18',
    itemBase: 'Ko Rune',
    imageFilename: 'ko_rune.png',
    name: 'Ko',
    link: 'https://d2runewizard.com/runes/Ko',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'fal',
    code: 'r19',
    itemBase: 'Fal Rune',
    imageFilename: 'fal_rune.png',
    name: 'Fal',
    link: 'https://d2runewizard.com/runes/Fal',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'lem',
    code: 'r20',
    itemBase: 'Lem Rune',
    imageFilename: 'lem_rune.png',
    name: 'Lem',
    link: 'https://d2runewizard.com/runes/Lem',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'pul',
    code: 'r21',
    itemBase: 'Pul Rune',
    imageFilename: 'pul_rune.png',
    name: 'Pul',
    link: 'https://d2runewizard.com/runes/Pul',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'um',
    code: 'r22',
    itemBase: 'Um Rune',
    imageFilename: 'um_rune.png',
    name: 'Um',
    link: 'https://d2runewizard.com/runes/Um',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'mal',
    code: 'r23',
    itemBase: 'Mal Rune',
    imageFilename: 'mal_rune.png',
    name: 'Mal',
    link: 'https://d2runewizard.com/runes/Mal',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ist',
    code: 'r24',
    itemBase: 'Ist Rune',
    imageFilename: 'ist_rune.png',
    name: 'Ist',
    link: 'https://d2runewizard.com/runes/Ist',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'gul',
    code: 'r25',
    itemBase: 'Gul Rune',
    imageFilename: 'gul_rune.png',
    name: 'Gul',
    link: 'https://d2runewizard.com/runes/Gul',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'vex',
    code: 'r26',
    itemBase: 'Vex Rune',
    imageFilename: 'vex_rune.png',
    name: 'Vex',
    link: 'https://d2runewizard.com/runes/Vex',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ohm',
    code: 'r27',
    itemBase: 'Ohm Rune',
    imageFilename: 'ohm_rune.png',
    name: 'Ohm',
    link: 'https://d2runewizard.com/runes/Ohm',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'lo',
    code: 'r28',
    itemBase: 'Lo Rune',
    imageFilename: 'lo_rune.png',
    name: 'Lo',
    link: 'https://d2runewizard.com/runes/Lo',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'sur',
    code: 'r29',
    itemBase: 'Sur Rune',
    imageFilename: 'sur_rune.png',
    name: 'Sur',
    link: 'https://d2runewizard.com/runes/Sur',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'ber',
    code: 'r30',
    itemBase: 'Ber Rune',
    imageFilename: 'ber_rune.png',
    name: 'Ber',
    link: 'https://d2runewizard.com/runes/Ber',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'jah',
    code: 'r31',
    itemBase: 'Jah Rune',
    imageFilename: 'jah_rune.png',
    name: 'Jah',
    link: 'https://d2runewizard.com/runes/Jah',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'cham',
    code: 'r32',
    itemBase: 'Cham Rune',
    imageFilename: 'cham_rune.png',
    name: 'Cham',
    link: 'https://d2runewizard.com/runes/Cham',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
  {
    id: 'zod',
    code: 'r33',
    itemBase: 'Zod Rune',
    imageFilename: 'zod_rune.png',
    name: 'Zod',
    link: 'https://d2runewizard.com/runes/Zod',
    etherealType: 'none',
    type: 'rune',
    category: 'runes',
    subCategory: 'runes',
    treasureClass: 'normal',
  },
];
