import type { Item } from '../types/grail';

export const sets: Item[] = [
  {
    id: 'angelicwings',
    name: 'Angelic Wings',
    link: 'https://diablo2.io/sets/angelic-wings-t1039.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: 'Angelic Raiment',
  },
  {
    id: 'angelichalo',
    name: 'Angelic Halo',
    link: 'https://diablo2.io/sets/angelic-halo-t1040.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    itemBase: 'Ring',
    treasureClass: 'normal',
    setName: 'Angelic Raiment',
  },
  {
    id: 'angelicmantle',
    name: 'Angelic Mantle',
    link: 'https://diablo2.io/sets/angelic-mantle-t1041.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'rng',
    itemBase: 'Ring Mail',
    setName: 'Angelic Raiment',
  },
  {
    id: 'angelicsickle',
    name: 'Angelic Sickle',
    link: 'https://diablo2.io/sets/angelic-sickle-t1042.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'sbr',
    itemBase: 'Sabre',
    setName: 'Angelic Raiment',
  },
  {
    id: 'arcannassign',
    name: "Arcanna's Sign",
    link: 'https://diablo2.io/sets/arcanna-s-sign-t1044.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: "Arcanna's Tricks",
  },
  {
    id: 'arcannashead',
    name: "Arcanna's Head",
    link: 'https://diablo2.io/sets/arcanna-s-head-t1045.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'skp',
    itemBase: 'Skull Cap',
    setName: "Arcanna's Tricks",
  },
  {
    id: 'arcannasflesh',
    name: "Arcanna's Flesh",
    link: 'https://diablo2.io/sets/arcanna-s-flesh-t1046.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'ltp',
    itemBase: 'Light Plate',
    setName: "Arcanna's Tricks",
  },
  {
    id: 'arcannasdeathwand',
    name: "Arcanna's Deathwand",
    link: 'https://diablo2.io/sets/arcanna-s-deathwand-t1047.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'normal',
    code: 'wst',
    itemBase: 'War Staff',
    setName: "Arcanna's Tricks",
  },
  {
    id: 'arcticmitts',
    name: 'Arctic Mitts',
    link: 'https://diablo2.io/sets/arctic-mitts-t1049.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'tgl',
    itemBase: 'Light Gauntlets',
    setName: 'Arctic Gear',
  },
  {
    id: 'arcticbinding',
    name: 'Arctic Binding',
    link: 'https://diablo2.io/sets/arctic-binding-t1050.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'vbl',
    itemBase: 'Light Belt',
    setName: 'Arctic Gear',
  },
  {
    id: 'arcticfurs',
    name: 'Arctic Furs',
    link: 'https://diablo2.io/sets/arctic-furs-t1051.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'qui',
    itemBase: 'Quilted Armor',
    setName: 'Arctic Gear',
  },
  {
    id: 'arctichorn',
    name: 'Arctic Horn',
    link: 'https://diablo2.io/sets/arctic-horn-t1052.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'swb',
    itemBase: 'Short War Bow',
    setName: 'Arctic Gear',
  },
  {
    id: 'berserkershatchet',
    name: "Berserker's Hatchet",
    link: 'https://diablo2.io/sets/berserker-s-hatchet-t1054.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'normal',
    code: '2ax',
    itemBase: 'Double Axe',
    setName: "Berserker's Arsenal",
  },
  {
    id: 'berserkershauberk',
    name: "Berserker's Hauberk",
    link: 'https://diablo2.io/sets/berserker-s-hauberk-t1055.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'spl',
    itemBase: 'Splint Mail',
    setName: "Berserker's Arsenal",
  },
  {
    id: 'berserkersheadgear',
    name: "Berserker's Headgear",
    link: 'https://diablo2.io/sets/berserker-s-headgear-t1056.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'hlm',
    itemBase: 'Helm',
    setName: "Berserker's Arsenal",
  },
  {
    id: 'cathansseal',
    name: "Cathan's Seal",
    link: 'https://diablo2.io/sets/cathan-s-seal-t31.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    itemBase: 'Ring',
    treasureClass: 'normal',
    setName: "Cathan's Traps",
  },
  {
    id: 'cathanssigil',
    name: "Cathan's Sigil",
    link: 'https://diablo2.io/sets/cathan-s-sigil-t32.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: "Cathan's Traps",
  },
  {
    id: 'cathansvisage',
    name: "Cathan's Visage",
    link: 'https://diablo2.io/sets/cathan-s-visage-t4.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'msk',
    itemBase: 'Mask',
    setName: "Cathan's Traps",
  },
  {
    id: 'cathansmesh',
    name: "Cathan's Mesh",
    link: 'https://diablo2.io/sets/cathan-s-mesh-t33.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'chn',
    itemBase: 'Chain Mail',
    setName: "Cathan's Traps",
  },
  {
    id: 'cathansrule',
    name: "Cathan's Rule",
    link: 'https://diablo2.io/sets/cathan-s-rule-t30.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'normal',
    code: 'bst',
    itemBase: 'Battle Staff',
    setName: "Cathan's Traps",
  },
  {
    id: 'civerbscudgel',
    name: "Civerb's Cudgel",
    link: 'https://diablo2.io/sets/civerb-s-cudgel-t1061.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_maces',
    treasureClass: 'normal',
    code: 'gsc',
    itemBase: 'Grand Scepter',
    setName: "Civerb's Vestments",
  },
  {
    id: 'civerbsward',
    name: "Civerb's Ward",
    link: 'https://diablo2.io/sets/civerb-s-ward-t1062.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'lrg',
    itemBase: 'Large Shield',
    setName: "Civerb's Vestments",
  },
  {
    id: 'civerbsicon',
    name: "Civerb's Icon",
    link: 'https://diablo2.io/sets/civerb-s-icon-t1063.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: "Civerb's Vestments",
  },
  {
    id: 'cleglawstooth',
    name: "Cleglaw's Tooth",
    link: 'https://diablo2.io/sets/cleglaw-s-tooth-t1065.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'lsd',
    itemBase: 'Long Sword',
    setName: "Cleglaw's Brace",
  },
  {
    id: 'cleglawsclaw',
    name: "Cleglaw's Claw",
    link: 'https://diablo2.io/sets/cleglaw-s-claw-t1066.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'sml',
    itemBase: 'Small Shield',
    setName: "Cleglaw's Brace",
  },
  {
    id: 'cleglawspincers',
    name: "Cleglaw's Pincers",
    link: 'https://diablo2.io/sets/cleglaw-s-pincers-t1067.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'mgl',
    itemBase: 'Chain Gloves',
    setName: "Cleglaw's Brace",
  },
  {
    id: 'deathstouch',
    name: "Death's Touch",
    link: 'https://diablo2.io/sets/death-s-touch-t1073.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'wsd',
    itemBase: 'War Sword',
    setName: "Death's Disguise",
  },
  {
    id: 'deathsguard',
    name: "Death's Guard",
    link: 'https://diablo2.io/sets/death-s-guard-t1074.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'lbl',
    itemBase: 'Sash',
    setName: "Death's Disguise",
  },
  {
    id: 'deathshand',
    name: "Death's Hand",
    link: 'https://diablo2.io/sets/death-s-hand-t1075.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'lgl',
    itemBase: 'Leather Gloves',
    setName: "Death's Disguise",
  },
  {
    id: 'hsarusironstay',
    name: "Hsarus' Iron Stay",
    link: 'https://diablo2.io/sets/hsarus-iron-stay-t1087.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'mbl',
    itemBase: 'Belt',
    setName: "Hsaru's Defense",
  },
  {
    id: 'hsarusironfist',
    name: "Hsarus' Iron Fist",
    link: 'https://diablo2.io/sets/hsarus-iron-fist-t1088.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'buc',
    itemBase: 'Buckler',
    setName: "Hsaru's Defense",
  },
  {
    id: 'hsarusironheel',
    name: "Hsarus' Iron Heel",
    link: 'https://diablo2.io/sets/hsarus-iron-heel-t1089.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'mbt',
    itemBase: 'Chain Boots',
    setName: "Hsaru's Defense",
  },
  {
    id: 'infernalsign',
    name: 'Infernal Sign',
    link: 'https://diablo2.io/sets/infernal-sign-t1100.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'tbl',
    itemBase: 'Heavy Belt',
    setName: 'Infernal Tools',
  },
  {
    id: 'infernaltorch',
    name: 'Infernal Torch',
    link: 'https://diablo2.io/sets/infernal-torch-t1101.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'normal',
    code: 'gwn',
    itemBase: 'Grim Wand',
    setName: 'Infernal Tools',
  },
  {
    id: 'infernalcranium',
    name: 'Infernal Cranium',
    link: 'https://diablo2.io/sets/infernal-cranium-t1102.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'cap',
    itemBase: 'Cap',
    setName: 'Infernal Tools',
  },
  {
    id: 'irathascoil',
    name: "Iratha's Coil",
    link: 'https://diablo2.io/sets/iratha-s-coil-t1104.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'crn',
    itemBase: 'Crown',
    setName: "Iratha's Finery",
  },
  {
    id: 'irathascuff',
    name: "Iratha's Cuff",
    link: 'https://diablo2.io/sets/iratha-s-cuff-t1105.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'tgl',
    itemBase: 'Light Gauntlets',
    setName: "Iratha's Finery",
  },
  {
    id: 'irathascord',
    name: "Iratha's Cord",
    link: 'https://diablo2.io/sets/iratha-s-cord-t1106.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'tbl',
    itemBase: 'Heavy Belt',
    setName: "Iratha's Finery",
  },
  {
    id: 'irathascollar',
    name: "Iratha's Collar",
    link: 'https://diablo2.io/sets/iratha-s-collar-t1107.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: "Iratha's Finery",
  },
  {
    id: 'isenhartslightbrand',
    name: "Isenhart's Lightbrand",
    link: 'https://diablo2.io/sets/isenhart-s-lightbrand-t1109.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'bsd',
    itemBase: 'Broad Sword',
    setName: "Isenhart's Armory",
  },
  {
    id: 'isenhartscase',
    name: "Isenhart's Case",
    link: 'https://diablo2.io/sets/isenhart-s-case-t1110.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'brs',
    itemBase: 'Breast Plate',
    setName: "Isenhart's Armory",
  },
  {
    id: 'isenhartshorns',
    name: "Isenhart's Horns",
    link: 'https://diablo2.io/sets/isenhart-s-horns-t1111.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'fhl',
    itemBase: 'Full Helm',
    setName: "Isenhart's Armory",
  },
  {
    id: 'isenhartsparry',
    name: "Isenhart's Parry",
    link: 'https://diablo2.io/sets/isenhart-s-parry-t1112.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'gts',
    itemBase: 'Gothic Shield',
    setName: "Isenhart's Armory",
  },
  {
    id: 'milabregasrod',
    name: "Milabrega's Rod",
    link: 'https://diablo2.io/sets/milabrega-s-rod-t1120.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_maces',
    treasureClass: 'normal',
    code: 'wsp',
    itemBase: 'War Scepter',
    setName: "Milabrega's Regalia",
  },
  {
    id: 'milabregasrobe',
    name: "Milabrega's Robe",
    link: 'https://diablo2.io/sets/milabrega-s-robe-t1121.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'aar',
    itemBase: 'Ancient Armor',
    setName: "Milabrega's Regalia",
  },
  {
    id: 'milabregasdiadem',
    name: "Milabrega's Diadem",
    link: 'https://diablo2.io/sets/milabrega-s-diadem-t1122.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'crn',
    itemBase: 'Crown',
    setName: "Milabrega's Regalia",
  },
  {
    id: 'milabregasorb',
    name: "Milabrega's Orb",
    link: 'https://diablo2.io/sets/milabrega-s-orb-t1123.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'kit',
    itemBase: 'Kite Shield',
    setName: "Milabrega's Regalia",
  },
  {
    id: 'sigonsshelter',
    name: "Sigon's Shelter",
    link: 'https://diablo2.io/sets/sigon-s-shelter-t1147.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'gth',
    itemBase: 'Gothic Plate',
    setName: "Sigon's Complete Steel",
  },
  {
    id: 'sigonsvisor',
    name: "Sigon's Visor",
    link: 'https://diablo2.io/sets/sigon-s-visor-t1148.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'ghm',
    itemBase: 'Great Helm',
    setName: "Sigon's Complete Steel",
  },
  {
    id: 'sigonsguard',
    name: "Sigon's Guard",
    link: 'https://diablo2.io/sets/sigon-s-guard-t1149.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'tow',
    itemBase: 'Tower Shield',
    setName: "Sigon's Complete Steel",
  },
  {
    id: 'sigonsgage',
    name: "Sigon's Gage",
    link: 'https://diablo2.io/sets/sigon-s-gage-t1150.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'hgl',
    itemBase: 'Gauntlets',
    setName: "Sigon's Complete Steel",
  },
  {
    id: 'sigonssabot',
    name: "Sigon's Sabot",
    link: 'https://diablo2.io/sets/sigon-s-sabot-t1151.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'hbt',
    itemBase: 'Greaves',
    setName: "Sigon's Complete Steel",
  },
  {
    id: 'sigonswrap',
    name: "Sigon's Wrap",
    link: 'https://diablo2.io/sets/sigon-s-wrap-t1152.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'hbl',
    itemBase: 'Plated Belt',
    setName: "Sigon's Complete Steel",
  },
  {
    id: 'tancredsskull',
    name: "Tancred's Skull",
    link: 'https://diablo2.io/sets/tancred-s-skull-t1160.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'bhm',
    itemBase: 'Bone Helm',
    setName: "Tancred's Battlegear",
  },
  {
    id: 'tancredsweird',
    name: "Tancred's Weird",
    link: 'https://diablo2.io/sets/tancred-s-weird-t1161.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: "Tancred's Battlegear",
  },
  {
    id: 'tancredshobnails',
    name: "Tancred's Hobnails",
    link: 'https://diablo2.io/sets/tancred-s-hobnails-t1162.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'lbt',
    itemBase: 'Boots',
    setName: "Tancred's Battlegear",
  },
  {
    id: 'tancredsspine',
    name: "Tancred's Spine",
    link: 'https://diablo2.io/sets/tancred-s-spine-t1163.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'ful',
    itemBase: 'Full Plate Mail',
    setName: "Tancred's Battlegear",
  },
  {
    id: 'tancredscrowbill',
    name: "Tancred's Crowbill",
    link: 'https://diablo2.io/sets/tancred-s-crowbill-t1164.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_maces',
    treasureClass: 'normal',
    code: 'mpi',
    itemBase: 'Military Pick',
    setName: "Tancred's Battlegear",
  },
  {
    id: 'vidalassnare',
    name: "Vidala's Snare",
    link: 'https://diablo2.io/sets/vidala-s-snare-t1178.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: "Vidala's Rig",
  },
  {
    id: 'vidalasambush',
    name: "Vidala's Ambush",
    link: 'https://diablo2.io/sets/vidala-s-ambush-t1179.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'lea',
    itemBase: 'Leather Armor',
    setName: "Vidala's Rig",
  },
  {
    id: 'vidalasfetlock',
    name: "Vidala's Fetlock",
    link: 'https://diablo2.io/sets/vidala-s-fetlock-t1180.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'tbt',
    itemBase: 'Light Plated Boots',
    setName: "Vidala's Rig",
  },
  {
    id: 'vidalasbarb',
    name: "Vidala's Barb",
    link: 'https://diablo2.io/sets/vidala-s-barb-t1181.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'lbb',
    itemBase: 'Long Battle Bow',
    setName: "Vidala's Rig",
  },
  {
    id: 'aldursrhythm',
    name: "Aldur's Rhythm",
    link: 'https://diablo2.io/sets/aldur-s-rhythm-t1034.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_maces',
    treasureClass: 'exceptional',
    code: '9mt',
    itemBase: 'Jagged Star',
    setName: "Aldur's Watchtower",
  },
  {
    id: 'aldursstonygaze',
    name: "Aldur's Stony Gaze",
    link: 'https://diablo2.io/sets/aldur-s-stony-gaze-t1035.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'druid',
    treasureClass: 'exceptional',
    code: 'dr8',
    itemBase: 'Stag Bow',
    setName: "Aldur's Watchtower",
  },
  {
    id: 'aldursdeception',
    name: "Aldur's Deception",
    link: 'https://diablo2.io/sets/aldur-s-deception-t1036.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'uul',
    itemBase: 'Lacquered Plate',
    setName: "Aldur's Watchtower",
  },
  {
    id: 'aldursadvance',
    name: "Aldur's Advance",
    link: 'https://diablo2.io/sets/aldur-s-advance-t1037.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'exceptional',
    code: 'xtb',
    itemBase: 'Battle Boots',
    setName: "Aldur's Watchtower",
  },
  {
    id: 'bulkathossacredcharge',
    name: "Bul-Kathos' Sacred Charge",
    link: 'https://diablo2.io/sets/bul-kathos-sacred-charge-t1058.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'elite',
    code: '7gd',
    itemBase: 'Glorious Axe',
    setName: "Bul-Kathos' Children",
  },
  {
    id: 'bulkathostribalguardian',
    name: "Bul-Kathos' Tribal Guardian",
    link: 'https://diablo2.io/sets/bul-kathos-tribal-guardian-t1059.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'elite',
    code: '7b7',
    itemBase: 'Suwayyah',
    setName: "Bul-Kathos' Children",
  },
  {
    id: 'cowkingshorns',
    name: "Cow King's Horns",
    link: 'https://diablo2.io/sets/cow-king-s-horns-t1069.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xap',
    itemBase: 'War Hat',
    setName: "Cow King's Leathers",
  },
  {
    id: 'cowkingshide',
    name: "Cow King's Hide",
    link: 'https://diablo2.io/sets/cow-king-s-hide-t1070.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'stu',
    itemBase: 'Studded Leather',
    setName: "Cow King's Leathers",
  },
  {
    id: 'cowkingshooves',
    name: "Cow King's Hooves",
    link: 'https://diablo2.io/sets/cow-king-s-hooves-t1071.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'exceptional',
    code: 'vbt',
    itemBase: 'Heavy Boots',
    setName: "Cow King's Leathers",
  },
  {
    id: 'griswoldsredemption',
    name: "Griswold's Redemption",
    link: 'https://diablo2.io/sets/griswold-s-redemption-t1077.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_maces',
    treasureClass: 'elite',
    code: '7ws',
    itemBase: 'Caduceus',
    setName: "Griswold's Legacy",
  },
  {
    id: 'griswoldsvalor',
    name: "Griswold's Valor",
    link: 'https://diablo2.io/sets/griswold-s-valor-t1078.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'urn',
    itemBase: 'Corona',
    setName: "Griswold's Legacy",
  },
  {
    id: 'griswoldsheart',
    name: "Griswold's Heart",
    link: 'https://diablo2.io/sets/griswold-s-heart-t1079.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'xar',
    itemBase: 'Chaos Armor',
    setName: "Griswold's Legacy",
  },
  {
    id: 'griswoldshonor',
    name: "Griswold's Honor",
    link: 'https://diablo2.io/sets/griswold-s-honor-t1080.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'elite',
    code: 'paf',
    itemBase: 'Aerin Shield',
    setName: "Griswold's Legacy",
  },
  {
    id: 'dangoonsteaching',
    name: "Dangoon's Teaching",
    link: 'https://diablo2.io/sets/dangoon-s-teaching-t1082.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_maces',
    treasureClass: 'elite',
    code: '7ma',
    itemBase: 'Reinforced Mace',
    setName: "Heaven's Brethren",
  },
  {
    id: 'haemosusadamant',
    name: "Haemosu's Adamant",
    link: 'https://diablo2.io/sets/haemosu-s-adamant-t1083.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xrs',
    itemBase: 'Cuirass',
    setName: "Heaven's Brethren",
  },
  {
    id: 'taebaeksglory',
    name: "Taebaek's Glory",
    link: 'https://diablo2.io/sets/taebaek-s-glory-t1084.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'elite',
    code: 'uts',
    itemBase: 'Ward',
    setName: "Heaven's Brethren",
  },
  {
    id: 'ondalsalmighty',
    name: "Ondal's Almighty",
    link: 'https://diablo2.io/sets/ondal-s-almighty-t1085.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'uhm',
    itemBase: 'Spired Helm',
    setName: "Heaven's Brethren",
  },
  {
    id: 'hwaninsjustice',
    name: "Hwanin's Justice",
    link: 'https://diablo2.io/sets/hwanin-s-justice-t1091.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'exceptional',
    code: '9vo',
    itemBase: 'Bill',
    setName: "Hwanin's Majesty",
  },
  {
    id: 'hwaninsrefuge',
    name: "Hwanin's Refuge",
    link: 'https://diablo2.io/sets/hwanin-s-refuge-t1092.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xcl',
    itemBase: 'Tigulated Mail',
    setName: "Hwanin's Majesty",
  },
  {
    id: 'hwaninssplendor',
    name: "Hwanin's Splendor",
    link: 'https://diablo2.io/sets/hwanin-s-splendor-t1093.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xrn',
    itemBase: 'Grand Crown',
    setName: "Hwanin's Majesty",
  },
  {
    id: 'hwaninsblessing',
    name: "Hwanin's Blessing",
    link: 'https://diablo2.io/sets/hwanin-s-blessing-t1094.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'exceptional',
    code: 'mbl',
    itemBase: 'Belt',
    setName: "Hwanin's Majesty",
  },
  {
    id: 'immortalkingsstonecrusher',
    name: "Immortal King's Stone Crusher",
    link: 'https://diablo2.io/sets/immortal-king-s-stone-crusher-t58.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7m7',
    itemBase: 'Ogre Maul',
    setName: 'Immortal King',
  },
  {
    id: 'immortalkingswill',
    name: "Immortal King's Will",
    link: 'https://diablo2.io/sets/immortal-king-s-will-t1095.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'ba5',
    itemBase: 'Blade Talons',
    setName: 'Immortal King',
  },
  {
    id: 'immortalkingssoulcage',
    name: "Immortal King's Soul Cage",
    link: 'https://diablo2.io/sets/immortal-king-s-soul-cage-t1096.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'uar',
    itemBase: 'Sacred Armor',
    setName: 'Immortal King',
  },
  {
    id: 'immortalkingsdetail',
    name: "Immortal King's Detail",
    link: 'https://diablo2.io/sets/immortal-king-s-detail-t59.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'elite',
    code: 'zhb',
    itemBase: 'War Belt',
    setName: 'Immortal King',
  },
  {
    id: 'immortalkingsforge',
    name: "Immortal King's Forge",
    link: 'https://diablo2.io/sets/immortal-king-s-forge-t1097.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'elite',
    code: 'xhg',
    itemBase: 'War Gauntlets',
    setName: 'Immortal King',
  },
  {
    id: 'immortalkingspillar',
    name: "Immortal King's Pillar",
    link: 'https://diablo2.io/sets/immortal-king-s-pillar-t1098.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'elite',
    code: 'xhb',
    itemBase: 'War Boots',
    setName: 'Immortal King',
  },
  {
    id: 'mavinascaster',
    name: "M'avina's Caster",
    link: 'https://diablo2.io/sets/m-avina-s-caster-t1114.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'amazon',
    treasureClass: 'elite',
    code: 'amb',
    itemBase: 'Ceremonial Spear',
    setName: "M'avina's Battle Hymn",
  },
  {
    id: 'mavinasembrace',
    name: "M'avina's Embrace",
    link: 'https://diablo2.io/sets/m-avina-s-embrace-t1115.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'uld',
    itemBase: 'Kraken Shell',
    setName: "M'avina's Battle Hymn",
  },
  {
    id: 'mavinastruesight',
    name: "M'avina's True Sight",
    link: 'https://diablo2.io/sets/m-avina-s-true-sight-t1116.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'ci3',
    itemBase: 'Greater Talons',
    setName: "M'avina's Battle Hymn",
  },
  {
    id: 'mavinastenet',
    name: "M'avina's Tenet",
    link: 'https://diablo2.io/sets/m-avina-s-tenet-t1117.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'elite',
    code: 'zvb',
    itemBase: 'Sharkskin Belt',
    setName: "M'avina's Battle Hymn",
  },
  {
    id: 'mavinasicyclutch',
    name: "M'avina's Icy Clutch",
    link: 'https://diablo2.io/sets/m-avina-s-icy-clutch-t1118.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'elite',
    code: 'xtg',
    itemBase: 'Battle Gauntlets',
    setName: "M'avina's Battle Hymn",
  },
  {
    id: 'najscirclet',
    name: "Naj's Circlet",
    link: 'https://diablo2.io/sets/naj-s-circlet-t1125.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'ci0',
    itemBase: 'Scissors Katar',
    setName: "Naj's Ancient Vestige",
  },
  {
    id: 'najslightplate',
    name: "Naj's Light Plate",
    link: 'https://diablo2.io/sets/naj-s-light-plate-t1126.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'ult',
    itemBase: 'Heater',
    setName: "Naj's Ancient Vestige",
  },
  {
    id: 'najspuzzler',
    name: "Naj's Puzzler",
    link: 'https://diablo2.io/sets/naj-s-puzzler-t1127.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'elite',
    code: '6cs',
    itemBase: 'Elder Staff',
    setName: "Naj's Ancient Vestige",
  },
  {
    id: 'natalyasmark',
    name: "Natalya's Mark",
    link: 'https://diablo2.io/sets/natalya-s-mark-t1129.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'assassin',
    treasureClass: 'elite',
    code: '7lw',
    itemBase: 'Runic Talons',
    setName: "Natalya's Odium",
  },
  {
    id: 'natalyasshadow',
    name: "Natalya's Shadow",
    link: 'https://diablo2.io/sets/natalya-s-shadow-t1130.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'ucl',
    itemBase: 'Loricated Mail',
    setName: "Natalya's Odium",
  },
  {
    id: 'natalyastotem',
    name: "Natalya's Totem",
    link: 'https://diablo2.io/sets/natalya-s-totem-t1131.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'xh9',
    itemBase: 'Grim Helm',
    setName: "Natalya's Odium",
  },
  {
    id: 'natalyassoul',
    name: "Natalya's Soul",
    link: 'https://diablo2.io/sets/natalya-s-soul-t1132.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'elite',
    code: 'xmb',
    itemBase: 'Mesh Boots',
    setName: "Natalya's Odium",
  },
  {
    id: 'whitstansguard',
    name: "Whitstan's Guard",
    link: 'https://diablo2.io/sets/whitstan-s-guard-t1134.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xml',
    itemBase: 'Round Shield',
    setName: "Orphan's Call",
  },
  {
    id: 'guillaumesface',
    name: "Guillaume's Face",
    link: 'https://diablo2.io/sets/guillaume-s-face-t1135.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xhm',
    itemBase: 'Winged Helm',
    setName: "Orphan's Call",
  },
  {
    id: 'wilhelmspride',
    name: "Wilhelm's Pride",
    link: 'https://diablo2.io/sets/wilhelm-s-pride-t1136.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'exceptional',
    code: 'ztb',
    itemBase: 'Battle Belt',
    setName: "Orphan's Call",
  },
  {
    id: 'magnusskin',
    name: "Magnus' Skin",
    link: 'https://diablo2.io/sets/magnus-skin-t1137.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'exceptional',
    code: 'xvg',
    itemBase: 'Sharkskin Gloves',
    setName: "Orphan's Call",
  },
  {
    id: 'sanderssuperstition',
    name: "Sander's Superstition",
    link: 'https://diablo2.io/sets/sander-s-superstition-t60.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'normal',
    code: 'bwn',
    itemBase: 'Bone Wand',
    setName: "Sander's Folly",
  },
  {
    id: 'sandersparagon',
    name: "Sander's Paragon",
    link: 'https://diablo2.io/sets/sander-s-paragon-t1139.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'cap',
    itemBase: 'Cap',
    setName: "Sander's Folly",
  },
  {
    id: 'sanderstaboo',
    name: "Sander's Taboo",
    link: 'https://diablo2.io/sets/sander-s-taboo-t1140.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'vgl',
    itemBase: 'Heavy Gloves',
    setName: "Sander's Folly",
  },
  {
    id: 'sandersriprap',
    name: "Sander's Riprap",
    link: 'https://diablo2.io/sets/sander-s-riprap-t1141.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'vbt',
    itemBase: 'Heavy Boots',
    setName: "Sander's Folly",
  },
  {
    id: 'sazabiscobaltredeemer',
    name: "Sazabi's Cobalt Redeemer",
    link: 'https://diablo2.io/sets/sazabi-s-cobalt-redeemer-t1143.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'elite',
    code: '7ls',
    itemBase: 'Stalagmite',
    setName: "Sazabi's Grand Tribute",
  },
  {
    id: 'sazabisghostliberator',
    name: "Sazabi's Ghost Liberator",
    link: 'https://diablo2.io/sets/sazabi-s-ghost-liberator-t1144.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'upl',
    itemBase: 'Balrog Skin',
    setName: "Sazabi's Grand Tribute",
  },
  {
    id: 'sazabismentalsheath',
    name: "Sazabi's Mental Sheath",
    link: 'https://diablo2.io/sets/sazabi-s-mental-sheath-t1145.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'xhl',
    itemBase: 'Basinet',
    setName: "Sazabi's Grand Tribute",
  },
  {
    id: 'talrashasadjudication',
    name: "Tal Rasha's Adjudication",
    link: 'https://diablo2.io/sets/tal-rasha-s-adjudication-t1154.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: "Tal Rasha's Wrappings",
  },
  {
    id: 'talrashaslidlesseye',
    name: "Tal Rasha's Lidless Eye",
    link: 'https://diablo2.io/sets/tal-rasha-s-lidless-eye-t1155.html',
    etherealType: 'none',
    type: 'set',
    category: 'weapons',
    subCategory: 'sorceress',
    treasureClass: 'exceptional',
    code: 'oba',
    itemBase: 'Wrist Blade',
    setName: "Tal Rasha's Wrappings",
  },
  {
    id: 'talrashasguardianship',
    name: "Tal Rasha's Guardianship",
    link: 'https://diablo2.io/sets/tal-rasha-s-guardianship-t1156.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'uld',
    itemBase: 'Kraken Shell',
    setName: "Tal Rasha's Wrappings",
  },
  {
    id: 'talrashashoradriccrest',
    name: "Tal Rasha's Horadric Crest",
    link: 'https://diablo2.io/sets/tal-rasha-s-horadric-crest-t1157.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xsk',
    itemBase: 'Death Mask',
    setName: "Tal Rasha's Wrappings",
  },
  {
    id: 'talrashasfinespuncloth',
    name: "Tal Rasha's Fine Spun Cloth",
    link: 'https://diablo2.io/sets/tal-rasha-s-fine-spun-cloth-t1158.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'exceptional',
    code: 'zmb',
    itemBase: 'Mesh Belt',
    setName: "Tal Rasha's Wrappings",
  },
  {
    id: 'darkadherent',
    name: 'Dark Adherent',
    link: 'https://diablo2.io/sets/dark-adherent-t1166.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'uui',
    itemBase: 'Dusk Shroud',
    setName: 'The Disciple',
  },
  {
    id: 'credendum',
    name: 'Credendum',
    link: 'https://diablo2.io/sets/credendum-t1167.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'elite',
    code: 'umc',
    itemBase: 'Mithril Coil',
    setName: 'The Disciple',
  },
  {
    id: 'layingofhands',
    name: 'Laying of Hands',
    link: 'https://diablo2.io/sets/laying-of-hands-t1168.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'elite',
    code: 'uts',
    itemBase: 'Ward',
    setName: 'The Disciple',
  },
  {
    id: 'riteofpassage',
    name: 'Rite of Passage',
    link: 'https://diablo2.io/sets/rite-of-passage-t1169.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'elite',
    code: 'xlb',
    itemBase: 'Demonhide Boots',
    setName: 'The Disciple',
  },
  {
    id: 'tellingofbeads',
    name: 'Telling of Beads',
    link: 'https://diablo2.io/sets/telling-of-beads-t1170.html',
    etherealType: 'none',
    type: 'set',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
    setName: 'The Disciple',
  },
  {
    id: 'trangoulsguise',
    name: "Trang-Oul's Guise",
    link: 'https://diablo2.io/sets/trang-oul-s-guise-t1172.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'uh9',
    itemBase: 'Bone Visage',
    setName: "Trang-Oul's Avatar",
  },
  {
    id: 'trangoulsscales',
    name: "Trang-Oul's Scales",
    link: 'https://diablo2.io/sets/trang-oul-s-scales-t1173.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'xul',
    itemBase: 'Embossed Plate',
    setName: "Trang-Oul's Avatar",
  },
  {
    id: 'trangoulsgirth',
    name: "Trang-Oul's Girth",
    link: 'https://diablo2.io/sets/trang-oul-s-girth-t1174.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'elite',
    code: 'umc',
    itemBase: 'Mithril Coil',
    setName: "Trang-Oul's Avatar",
  },
  {
    id: 'trangoulsclaws',
    name: "Trang-Oul's Claws",
    link: 'https://diablo2.io/sets/trang-oul-s-claws-t1175.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'elite',
    code: 'xmg',
    itemBase: 'Heavy Bracers',
    setName: "Trang-Oul's Avatar",
  },
  {
    id: 'trangoulswing',
    name: "Trang-Oul's Wing",
    link: 'https://diablo2.io/sets/trang-oul-s-wing-t1176.html',
    etherealType: 'none',
    type: 'set',
    category: 'armor',
    subCategory: 'necromancer',
    treasureClass: 'elite',
    code: 'ne9',
    itemBase: 'Preserved Head',
    setName: "Trang-Oul's Avatar",
  },
];
