blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/hyperremix/d2r-arcane-tracker/discussions
    about: Ask questions and discuss ideas with the community
  - name: Contributing Guidelines
    url: https://github.com/hyperremix/d2r-arcane-tracker/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to D2R Arcane Tracker
