import type { Item } from '../../types/grail';

export const belts: Item[] = [
  {
    id: 'lenymo',
    name: 'Lenymo',
    link: 'https://diablo2.io/uniques/lenymo-t844.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'lbl',
    itemBase: 'Sash',
    imageFilename: 'sash_l.png',
  },
  {
    id: 'snakecord',
    name: 'Snakecord',
    link: 'https://diablo2.io/uniques/snakecord-t914.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'vbl',
    itemBase: 'Light Belt',
    imageFilename: 'light_belt.png',
  },
  {
    id: 'nightsmoke',
    name: 'Nightsmoke',
    link: 'https://diablo2.io/uniques/nightsmoke-t864.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'mbl',
    itemBase: 'Belt',
    imageFilename: 'belt_m.png',
  },
  {
    id: 'goldwrap',
    name: 'Goldwrap',
    link: 'https://diablo2.io/uniques/goldwrap-t787.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'tbl',
    itemBase: 'Heavy Belt',
    imageFilename: 'heavy_belt.png',
  },
  {
    id: 'bladebuckle',
    name: 'Bladebuckle',
    link: 'https://diablo2.io/uniques/bladebuckle-t697.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'normal',
    code: 'hbl',
    itemBase: 'Plated Belt',
    imageFilename: 'girdle_h.png',
  },
  {
    id: 'stringofears',
    name: 'String of Ears',
    link: 'https://diablo2.io/uniques/string-of-ears-t950.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'exceptional',
    code: 'zlb',
    itemBase: 'Demonhide Sash',
    imageFilename: 'sash_l.png',
  },
  {
    id: 'razortail',
    name: 'Razortail',
    link: 'https://diablo2.io/uniques/razortail-t887.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'exceptional',
    code: 'zvb',
    itemBase: 'Sharkskin Belt',
    imageFilename: 'light_belt.png',
  },
  {
    id: 'gloomstrap',
    name: "Gloom's Trap",
    link: 'https://diablo2.io/uniques/gloom-s-trap-t783.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'exceptional',
    code: 'zmb',
    itemBase: 'Mesh Belt',
    imageFilename: 'belt_m.png',
  },
  {
    id: 'snowclash',
    name: 'Snowclash',
    link: 'https://diablo2.io/uniques/snowclash-t915.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'exceptional',
    code: 'ztb',
    itemBase: 'Battle Belt',
    imageFilename: 'heavy_belt.png',
  },
  {
    id: 'thundergodsvigor',
    name: "Thundergod's Vigor",
    link: 'https://diablo2.io/uniques/thundergod-s-vigor-t38.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'exceptional',
    code: 'zhb',
    itemBase: 'War Belt',
    imageFilename: 'girdle_h.png',
  },
  {
    id: 'arachnidmesh',
    name: 'Arachnid Mesh',
    link: 'https://diablo2.io/uniques/arachnid-mesh-t671.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'elite',
    code: 'ulc',
    itemBase: 'Spiderweave Silk',
    imageFilename: 'sash_l.png',
  },
  {
    id: 'nosferatuscoil',
    name: "Nosferatu's Coil",
    link: 'https://diablo2.io/uniques/nosferatu-s-coil-t868.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'elite',
    code: 'uvc',
    itemBase: 'Vampirefang Belt',
    imageFilename: 'light_belt.png',
  },
  {
    id: 'verdungosheartycord',
    name: "Verdungo's Hearty Cord",
    link: 'https://diablo2.io/uniques/verdungo-s-hearty-cord-t1011.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'belts',
    treasureClass: 'elite',
    code: 'umc',
    itemBase: 'Mithril Coil',
    imageFilename: 'belt_m.png',
  },
];
