import type { Item } from '../../types/grail';

export const bodyArmors: Item[] = [
  {
    id: 'greyform',
    name: 'Greyform',
    link: 'https://diablo2.io/uniques/greyform-t793.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'qui',
    itemBase: 'Quilted Armor',
  },
  {
    id: 'blinkbatsform',
    name: "Blinkbat's Form",
    link: 'https://diablo2.io/uniques/blinkbat-s-form-t699.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'lea',
    itemBase: 'Leather Armor',
  },
  {
    id: 'thecenturion',
    name: 'The Centurion',
    link: 'https://diablo2.io/uniques/the-centurion-t961.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'hla',
    itemBase: 'Hard Leather Armor',
  },
  {
    id: 'twitchthroe',
    name: 'Twitchthroe',
    link: 'https://diablo2.io/uniques/twitchthroe-t1001.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'stu',
    itemBase: 'Studded Leather',
  },
  {
    id: 'darkglow',
    name: 'Darkglow',
    link: 'https://diablo2.io/uniques/darkglow-t740.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'rng',
    itemBase: 'Ring Mail',
  },
  {
    id: 'hawkmail',
    name: 'Hawkmail',
    link: 'https://diablo2.io/uniques/hawkmail-t803.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'scl',
    itemBase: 'Scale Mail',
  },
  {
    id: 'venomward',
    name: 'Venom Ward',
    link: 'https://diablo2.io/uniques/venom-ward-t1010.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'brs',
    itemBase: 'Breast Plate',
  },
  {
    id: 'sparkingmail',
    name: 'Sparking Mail',
    link: 'https://diablo2.io/uniques/sparking-mail-t919.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'chn',
    itemBase: 'Chain Mail',
  },
  {
    id: 'iceblink',
    name: 'Iceblink',
    link: 'https://diablo2.io/uniques/iceblink-t825.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'spl',
    itemBase: 'Splint Mail',
  },
  {
    id: 'heavenlygarb',
    name: 'Heavenly Garb',
    link: 'https://diablo2.io/uniques/heavenly-garb-t807.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'ltp',
    itemBase: 'Light Plate',
  },
  {
    id: 'rockfleece',
    name: 'Rockfleece',
    link: 'https://diablo2.io/uniques/rockfleece-t893.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'fld',
    itemBase: 'Field Plate',
  },
  {
    id: 'boneflesh',
    name: 'Boneflesh',
    link: 'https://diablo2.io/uniques/boneflesh-t709.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'plt',
    itemBase: 'Plate Mail',
  },
  {
    id: 'rattlecage',
    name: 'Rattlecage',
    link: 'https://diablo2.io/uniques/rattlecage-t882.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'gth',
    itemBase: 'Gothic Plate',
  },
  {
    id: 'goldskin',
    name: 'Goldskin',
    link: 'https://diablo2.io/uniques/goldskin-t785.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'ful',
    itemBase: 'Full Plate Mail',
  },
  {
    id: 'silksofthevictor',
    name: 'Silks of the Victor',
    link: 'https://diablo2.io/uniques/silks-of-the-victor-t2.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'normal',
    code: 'aar',
    itemBase: 'Ancient Armor',
  },
  {
    id: 'thespiritshroud',
    name: 'The Spirit Shroud',
    link: 'https://diablo2.io/uniques/the-spirit-shroud-t989.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xui',
    itemBase: 'Ghost Armor',
  },
  {
    id: 'skinofthevipermagi',
    name: 'Skin of the Vipermagi',
    link: 'https://diablo2.io/uniques/skin-of-the-vipermagi-t909.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xea',
    itemBase: 'Serpentskin Armor',
  },
  {
    id: 'skinoftheflayedone',
    name: 'Skin of the Flayed One',
    link: 'https://diablo2.io/uniques/skin-of-the-flayed-one-t908.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xla',
    itemBase: 'Demonhide Armor',
  },
  {
    id: 'ironpelt',
    name: 'Iron Pelt',
    link: 'https://diablo2.io/uniques/iron-pelt-t828.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xtu',
    itemBase: 'Trellised Armor',
  },
  {
    id: 'crowcaw',
    name: 'Crow Caw',
    link: 'https://diablo2.io/uniques/crow-caw-t733.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xcl',
    itemBase: 'Tigulated Mail',
  },
  {
    id: 'spiritforge',
    name: 'Spirit Forge',
    link: 'https://diablo2.io/uniques/spirit-forge-t926.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xng',
    itemBase: 'Linked Mail',
  },
  {
    id: 'durielsshell',
    name: "Duriel's Shell",
    link: 'https://diablo2.io/uniques/duriel-s-shell-t757.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xrs',
    itemBase: 'Cuirass',
  },
  {
    id: 'shaftstop',
    name: 'Shaftstop',
    link: 'https://diablo2.io/uniques/shaftstop-t905.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xhn',
    itemBase: 'Mesh Armor',
  },
  {
    id: 'skulldersire',
    name: "Skullder's Ire",
    link: 'https://diablo2.io/uniques/skullder-s-ire-t912.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xpl',
    itemBase: 'Russet Armor',
  },
  {
    id: 'queheganswisdom',
    name: "Que-Hegan's Wisdom",
    link: 'https://diablo2.io/uniques/que-hegan-s-wisdom-t878.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xtp',
    itemBase: 'Templar Coat',
  },
  {
    id: 'toothrow',
    name: 'Toothrow',
    link: 'https://diablo2.io/uniques/toothrow-t998.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xld',
    itemBase: 'Sharktooth Armor',
  },
  {
    id: 'guardianangel',
    name: 'Guardian Angel',
    link: 'https://diablo2.io/uniques/guardian-angel-t797.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xlt',
    itemBase: 'Mage Plate',
  },
  {
    id: 'atmaswail',
    name: "Atma's Wail",
    link: 'https://diablo2.io/uniques/atma-s-wail-t679.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xth',
    itemBase: 'Sharktooth Armor',
  },
  {
    id: 'blackhades',
    name: 'Black Hades',
    link: 'https://diablo2.io/uniques/black-hades-t688.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xul',
    itemBase: 'Embossed Plate',
  },
  {
    id: 'corpsemourn',
    name: 'Corpsemourn',
    link: 'https://diablo2.io/uniques/corpsemourn-t729.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'exceptional',
    code: 'xar',
    itemBase: 'Chaos Armor',
  },
  {
    id: 'ormusrobes',
    name: "Ormus' Robes",
    link: 'https://diablo2.io/uniques/ormus-robes-t870.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'uui',
    itemBase: 'Dusk Shroud',
  },
  {
    id: 'thegladiatorsbane',
    name: "The Gladiator's Bane",
    link: 'https://diablo2.io/uniques/the-gladiator-s-bane-t971.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'utu',
    itemBase: 'Wire Fleece',
  },
  {
    id: 'arkainesvalor',
    name: "Arkaine's Valor",
    link: 'https://diablo2.io/uniques/arkaine-s-valor-t673.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'upl',
    itemBase: 'Balrog Skin',
  },
  {
    id: 'leviathan',
    name: 'Leviathan',
    link: 'https://diablo2.io/uniques/leviathan-t845.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'uld',
    itemBase: 'Kraken Shell',
  },
  {
    id: 'steelcarapace',
    name: 'Steel Carapace',
    link: 'https://diablo2.io/uniques/steel-carapace-t930.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'uul',
    itemBase: 'Lacquered Plate',
  },
  {
    id: 'templarsmight',
    name: "Templar's Might",
    link: 'https://diablo2.io/uniques/templar-s-might-t957.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'uar',
    itemBase: 'Sacred Armor',
  },
  {
    id: 'tyraelsmight',
    name: "Tyrael's Might",
    link: 'https://diablo2.io/uniques/tyrael-s-might-t1002.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'body_armor',
    treasureClass: 'elite',
    code: 'uar',
    itemBase: 'Sacred Armor',
  },
];
