import type { Item } from '../../types/grail';

export const boots: Item[] = [
  {
    id: 'hotspur',
    name: 'Hotspur',
    link: 'https://diablo2.io/uniques/hotspur-t821.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'lbt',
  },
  {
    id: 'gorefoot',
    name: 'Gorefoot',
    link: 'https://diablo2.io/uniques/gorefoot-t789.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'vbt',
  },
  {
    id: 'treadsofcthon',
    name: 'Treads of Cthon',
    link: 'https://diablo2.io/uniques/treads-of-cthon-t1000.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'mbt',
  },
  {
    id: 'goblintoe',
    name: 'Goblin Toe',
    link: 'https://diablo2.io/uniques/goblin-toe-t784.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'tbt',
  },
  {
    id: 'tearhaunch',
    name: 'Tearhaunch',
    link: 'https://diablo2.io/uniques/tearhaunch-t956.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'normal',
    code: 'hbt',
  },
  {
    id: 'infernostride',
    name: 'Infernostride',
    link: 'https://diablo2.io/uniques/infernostride-t827.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'exceptional',
    code: 'xlb',
  },
  {
    id: 'waterwalk',
    name: 'Waterwalk',
    link: 'https://diablo2.io/uniques/waterwalk-t1019.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'exceptional',
    code: 'xvb',
  },
  {
    id: 'silkweave',
    name: 'Silkweave',
    link: 'https://diablo2.io/uniques/silkweave-t906.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'exceptional',
    code: 'xmb',
  },
  {
    id: 'wartraveler',
    name: 'War Traveler',
    link: 'https://diablo2.io/uniques/war-traveler-t1015.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'exceptional',
    code: 'xtb',
  },
  {
    id: 'gorerider',
    name: 'Gore Rider',
    link: 'https://diablo2.io/uniques/gore-rider-t788.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'exceptional',
    code: 'xhb',
  },
  {
    id: 'marrowwalk',
    name: 'Marrowwalk',
    link: 'https://diablo2.io/uniques/marrowwalk-t856.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'elite',
    code: 'umb1',
  },
  {
    id: 'sandstormtrek',
    name: 'Sandstorm Trek',
    link: 'https://diablo2.io/uniques/sandstorm-trek-t898.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'elite',
    code: 'uvb',
  },
  {
    id: 'shadowdancer',
    name: 'Shadow Dancer',
    link: 'https://diablo2.io/uniques/shadow-dancer-t902.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'boots',
    treasureClass: 'elite',
    code: 'uhb',
  },
];
