import type { Item } from '../../types/grail';

export const gloves: Item[] = [
  {
    id: 'thehandofbroc',
    name: 'The Hand of Broc',
    link: 'https://diablo2.io/uniques/the-hand-of-broc-t975.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'lgl',
  },
  {
    id: 'bloodfist',
    name: 'Bloodfist',
    link: 'https://diablo2.io/uniques/bloodfist-t702.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'vgl',
  },
  {
    id: 'chanceguards',
    name: 'Chance Guards',
    link: 'https://diablo2.io/uniques/chance-guards-t722.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'mgl',
  },
  {
    id: 'magefist',
    name: 'Magefist',
    link: 'https://diablo2.io/uniques/magefist-t851.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'tgl',
  },
  {
    id: 'frostburn',
    name: 'Frostburn',
    link: 'https://diablo2.io/uniques/frostburn-t772.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'normal',
    code: 'hgl',
  },
  {
    id: 'venomgrip',
    name: 'Venom Grip',
    link: 'https://diablo2.io/uniques/venom-grip-t1009.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'exceptional',
    code: 'xlg',
  },
  {
    id: 'gravepalm',
    name: 'Gravepalm',
    link: 'https://diablo2.io/uniques/gravepalm-t792.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'exceptional',
    code: 'xvg',
  },
  {
    id: 'ghoulhide',
    name: 'Ghoulhide',
    link: 'https://diablo2.io/uniques/ghoulhide-t778.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'exceptional',
    code: 'xmg',
  },
  {
    id: 'lavagout',
    name: 'Lava Gout',
    link: 'https://diablo2.io/uniques/lava-gout-t842.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'exceptional',
    code: 'xtg',
  },
  {
    id: 'hellmouth',
    name: 'Hellmouth',
    link: 'https://diablo2.io/uniques/hellmouth-t811.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'exceptional',
    code: 'xhg',
  },
  {
    id: 'draculsgrasp',
    name: "Dracul's Grasp",
    link: 'https://diablo2.io/uniques/dracul-s-grasp-t755.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'elite',
    code: 'uvg',
  },
  {
    id: 'souldrainer',
    name: 'Soul Drainer',
    link: 'https://diablo2.io/uniques/soul-drainer-t916.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'elite',
    code: 'umg',
  },
  {
    id: 'steelrend',
    name: 'Steelrend',
    link: 'https://diablo2.io/uniques/steelrend-t936.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'gloves',
    treasureClass: 'elite',
    code: 'uhg',
  },
];
