import type { Item } from '../../types/grail';

export const helms: Item[] = [
  {
    id: 'bigginsbonnet',
    name: "Biggin's Bonnet",
    link: 'https://diablo2.io/uniques/biggin-s-bonnet-t686.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'cap',
    itemBase: 'Cap',
  },
  {
    id: 'tarnhelm',
    name: 'Tarnhelm',
    link: 'https://diablo2.io/uniques/tarnhelm-t955.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'skp',
    itemBase: 'Skull Cap',
  },
  {
    id: 'coifofglory',
    name: 'Coif of Glory',
    link: 'https://diablo2.io/uniques/coif-of-glory-t726.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'hlm',
    itemBase: 'Helm',
  },
  {
    id: 'duskdeep',
    name: 'Duskdeep',
    link: 'https://diablo2.io/uniques/duskdeep-t758.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'fhl',
    itemBase: 'Full Helm',
  },
  {
    id: 'wormskull',
    name: 'Wormskull',
    link: 'https://diablo2.io/uniques/wormskull-t1030.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'bhm',
    itemBase: 'Bone Helm',
  },
  {
    id: 'howltusk',
    name: 'Howltusk',
    link: 'https://diablo2.io/uniques/howltusk-t822.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'ghm',
    itemBase: 'Great Helm',
  },
  {
    id: 'undeadcrown',
    name: 'Undead Crown',
    link: 'https://diablo2.io/uniques/undead-crown-t1005.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'crn',
    itemBase: 'Crown',
  },
  {
    id: 'thefaceofhorror',
    name: 'The Face of Horror',
    link: 'https://diablo2.io/uniques/the-face-of-horror-t967.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'normal',
    code: 'msk',
    itemBase: 'Mask',
  },
  {
    id: 'peasantcrown',
    name: 'Peasant Crown',
    link: 'https://diablo2.io/uniques/peasant-crown-t871.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xap',
    itemBase: 'War Hat',
  },
  {
    id: 'rockstopper',
    name: 'Rockstopper',
    link: 'https://diablo2.io/uniques/rockstopper-t894.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xkp',
    itemBase: 'Sallet',
  },
  {
    id: 'stealskull',
    name: 'Stealskull',
    link: 'https://diablo2.io/uniques/stealskull-t929.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xlm',
    itemBase: 'Casque',
  },
  {
    id: 'darksighthelm',
    name: 'Darksight Helm',
    link: 'https://diablo2.io/uniques/darksight-helm-t741.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xhl',
    itemBase: 'Basinet',
  },
  {
    id: 'vampiregaze',
    name: 'Vampire Gaze',
    link: 'https://diablo2.io/uniques/vampire-gaze-t1007.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xh9',
    itemBase: 'Grim Helm',
  },
  {
    id: 'valkyriewing',
    name: 'Valkyrie Wing',
    link: 'https://diablo2.io/uniques/valkyrie-wing-t1006.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xhm',
    itemBase: 'Winged Helm',
  },
  {
    id: 'crownofthieves',
    name: 'Crown of Thieves',
    link: 'https://diablo2.io/uniques/crown-of-thieves-t735.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xrn',
    itemBase: 'Grand Crown',
  },
  {
    id: 'blackhornsface',
    name: "Blackhorn's Face",
    link: 'https://diablo2.io/uniques/blackhorn-s-face-t691.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'exceptional',
    code: 'xsk',
    itemBase: 'Death Mask',
  },
  {
    id: 'andarielsvisage',
    name: "Andariel's Visage",
    link: 'https://diablo2.io/uniques/andariel-s-visage-t669.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'usk',
    itemBase: 'Demonhead',
  },
  {
    id: 'crownofages',
    name: 'Crown of Ages',
    link: 'https://diablo2.io/uniques/crown-of-ages-t734.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'urn',
    itemBase: 'Corona',
  },
  {
    id: 'giantskull',
    name: 'Giant Skull',
    link: 'https://diablo2.io/uniques/giant-skull-t779.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'uh9',
    itemBase: 'Bone Visage',
  },
  {
    id: 'harlequincrest',
    name: 'Harlequin Crest',
    link: 'https://diablo2.io/uniques/harlequin-crest-t37.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'uap',
    itemBase: 'Shako',
  },
  {
    id: 'nightwingsveil',
    name: "Nightwing's Veil",
    link: 'https://diablo2.io/uniques/nightwing-s-veil-t865.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'uhm',
    itemBase: 'Spired Helm',
  },
  {
    id: 'steelshade',
    name: 'Steel Shade',
    link: 'https://diablo2.io/uniques/steel-shade-t932.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'ulm',
    itemBase: 'Armet',
  },
  {
    id: 'veilofsteel',
    name: 'Veil of Steel',
    link: 'https://diablo2.io/uniques/veil-of-steel-t1008.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'uhm',
    itemBase: 'Spired Helm',
  },
  {
    id: 'kirasguardian',
    name: "Kira's Guardian",
    link: 'https://diablo2.io/uniques/kira-s-guardian-t835.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'ci2',
    itemBase: 'Greater Claws',
  },
  {
    id: 'griffonseye',
    name: "Griffon's Eye",
    link: 'https://diablo2.io/uniques/griffon-s-eye-t794.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'helms',
    treasureClass: 'elite',
    code: 'ci3',
    itemBase: 'Greater Talons',
  },
];
