import type { Item } from '../../types/grail';

export const shields: Item[] = [
  {
    id: 'peltalunata',
    name: 'Pelta Lunata',
    link: 'https://diablo2.io/uniques/pelta-lunata-t872.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'buc',
    itemBase: 'Buckler',
    imageFilename: 'pelta_lunata.png',
  },
  {
    id: 'umbraldisk',
    name: 'Umbral Disk',
    link: 'https://diablo2.io/uniques/umbral-disk-t1003.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'sml',
    itemBase: 'Small Shield',
    imageFilename: 'umbral_disk.png',
  },
  {
    id: 'stormguild',
    name: 'Stormguild',
    link: 'https://diablo2.io/uniques/stormguild-t942.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'lrg',
    itemBase: 'Large Shield',
    imageFilename: 'stormguild.png',
  },
  {
    id: 'swordbackhold',
    name: 'Swordback Hold',
    link: 'https://diablo2.io/uniques/swordback-hold-t953.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'spk',
    itemBase: 'Spiked Shield',
    imageFilename: 'swordback_hold.png',
  },
  {
    id: 'steelclash',
    name: 'Steelclash',
    link: 'https://diablo2.io/uniques/steelclash-t933.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'kit',
    itemBase: 'Kite Shield',
    imageFilename: 'steelclash.png',
  },
  {
    id: 'walloftheeyeless',
    name: 'Wall of the Eyeless',
    link: 'https://diablo2.io/uniques/wall-of-the-eyeless-t1014.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'bsh',
    itemBase: 'Bone Shield',
    imageFilename: 'wall_of_the_eyeless.png',
  },
  {
    id: 'bverritkeep',
    name: 'Bverrit Keep',
    link: 'https://diablo2.io/uniques/bverrit-keep-t718.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'tow',
    itemBase: 'Tower Shield',
    imageFilename: 'bverrit_keep.png',
  },
  {
    id: 'theward',
    name: 'The Ward',
    link: 'https://diablo2.io/uniques/the-ward-t992.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'normal',
    code: 'gts',
    itemBase: 'Gothic Shield',
    imageFilename: 'the_ward.png',
  },
  {
    id: 'visceratuant',
    name: 'Visceratuant',
    link: 'https://diablo2.io/uniques/visceratuant-t1013.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xuc',
    itemBase: 'Defender',
    imageFilename: 'small_shield.png',
  },
  {
    id: 'mosersblessedcircle',
    name: "Moser's Blessed Circle",
    link: 'https://diablo2.io/uniques/moser-s-blessed-circle-t861.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xml',
    itemBase: 'Round Shield',
    imageFilename: 'buckler.png',
  },
  {
    id: 'stormchaser',
    name: 'Stormchaser',
    link: 'https://diablo2.io/uniques/stormchaser-t940.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xrg',
    itemBase: 'Scutum',
    imageFilename: 'stormchaser.png',
  },
  {
    id: 'lanceguard',
    name: 'Lance Guard',
    link: 'https://diablo2.io/uniques/lance-guard-t839.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xpk',
    itemBase: 'Barbed Shield',
    imageFilename: 'lance_guard.png',
  },
  {
    id: 'tiamatsrebuke',
    name: "Tiamat's Rebuke",
    link: 'https://diablo2.io/uniques/tiamat-s-rebuke-t994.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xit',
    itemBase: 'Dragon Shield',
    imageFilename: 'kite_shield.png',
  },
  {
    id: 'lidlesswall',
    name: 'Lidless Wall',
    link: 'https://diablo2.io/uniques/lidless-wall-t846.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xsh',
    itemBase: 'Grim Shield',
    imageFilename: 'lidless_wall.png',
  },
  {
    id: 'gerkessanctuary',
    name: "Gerke's Sanctuary",
    link: 'https://diablo2.io/uniques/gerke-s-sanctuary-t775.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xow',
    itemBase: 'Pavise',
    imageFilename: 'tower_shield.png',
  },
  {
    id: 'radamentssphere',
    name: "Radament's Sphere",
    link: 'https://diablo2.io/uniques/radament-s-sphere-t879.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'exceptional',
    code: 'xts',
    itemBase: 'Ancient Shield',
    imageFilename: 'gothic_shield.png',
  },
  {
    id: 'blackoakshield',
    name: 'Blackoak Shield',
    link: 'https://diablo2.io/uniques/blackoak-shield-t693.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'elite',
    code: 'uml',
    itemBase: 'Luna',
    imageFilename: 'buckler.png',
  },
  {
    id: 'stormshield',
    name: 'Stormshield',
    link: 'https://diablo2.io/uniques/stormshield-t945.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'elite',
    code: 'uit',
    itemBase: 'Monarch',
    imageFilename: 'kite_shield.png',
  },
  {
    id: 'headhuntersglory',
    name: "Head Hunter's Glory",
    link: 'https://diablo2.io/uniques/head-hunter-s-glory-t804.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'elite',
    code: 'ush',
    itemBase: 'Troll Nest',
    imageFilename: 'falchion.png',
  },
  {
    id: 'medusasgaze',
    name: "Medusa's Gaze",
    link: 'https://diablo2.io/uniques/medusa-s-gaze-t857.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'elite',
    code: 'uow',
    itemBase: 'Aegis',
    imageFilename: 'tower_shield.png',
  },
  {
    id: 'spikethorn',
    name: 'Spike Thorn',
    link: 'https://diablo2.io/uniques/spike-thorn-t922.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'elite',
    code: 'upk',
    itemBase: 'Blade Barrier',
    imageFilename: 'swordback_hold.png',
  },
  {
    id: 'spiritward',
    name: 'Spirit Ward',
    link: 'https://diablo2.io/uniques/spirit-ward-t928.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'shields',
    treasureClass: 'elite',
    code: 'uts',
    itemBase: 'Ward',
    imageFilename: 'gothic_shield.png',
  },
];
