import type { Item } from '../../types/grail';

export const oneHandedAxes: Item[] = [
  {
    id: 'thegnasher',
    name: 'The Gnasher',
    link: 'https://diablo2.io/uniques/the-gnasher-t972.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'normal',
    code: 'hax',
  },
  {
    id: 'deathspade',
    name: 'Deathspade',
    link: 'https://diablo2.io/uniques/deathspade-t746.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'normal',
    code: 'axe',
  },
  {
    id: 'bladebone',
    name: 'Bladebone',
    link: 'https://diablo2.io/uniques/bladebone-t696.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'normal',
    code: '2ax',
  },
  {
    id: 'skullsplitter',
    name: 'Skull Splitter',
    link: 'https://diablo2.io/uniques/skull-splitter-t911.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'normal',
    code: 'mpi',
  },
  {
    id: 'rakescar',
    name: 'Rakescar',
    link: 'https://diablo2.io/uniques/rakescar-t881.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'normal',
    code: 'wax',
  },
  {
    id: 'coldkill',
    name: 'Coldkill',
    link: 'https://diablo2.io/uniques/coldkill-t727.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'exceptional',
    code: '9ha',
  },
  {
    id: 'butcherspupil',
    name: "Butcher's Pupil",
    link: 'https://diablo2.io/uniques/butcher-s-pupil-t717.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'exceptional',
    code: '9ax',
  },
  {
    id: 'islestrike',
    name: 'Islestrike',
    link: 'https://diablo2.io/uniques/islestrike-t830.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'exceptional',
    code: '92a',
  },
  {
    id: 'pompeiiswrath',
    name: "Pompeii's Wrath",
    link: 'https://diablo2.io/uniques/pompeii-s-wrath-t876.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'exceptional',
    code: '9mp',
  },
  {
    id: 'guardiannaga',
    name: 'Guardian Naga',
    link: 'https://diablo2.io/uniques/guardian-naga-t798.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'exceptional',
    code: '9wa',
  },
  {
    id: 'razorsedge',
    name: "Razor's Edge",
    link: 'https://diablo2.io/uniques/razor-s-edge-t886.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'elite',
    code: '7ha',
  },
  {
    id: 'runemaster',
    name: 'Rune Master',
    link: 'https://diablo2.io/uniques/rune-master-t896.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'elite',
    code: '72a',
  },
  {
    id: 'cranebeak',
    name: 'Cranebeak',
    link: 'https://diablo2.io/uniques/cranebeak-t731.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'elite',
    code: '7mp',
  },
  {
    id: 'deathcleaver',
    name: 'Death Cleaver',
    link: 'https://diablo2.io/uniques/death-cleaver-t742.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_axes',
    treasureClass: 'elite',
    code: '7wa',
  },
];
