import type { Item } from '../../types/grail';

export const oneHandedClubs: Item[] = [
  {
    id: 'felloak',
    name: 'Felloak',
    link: 'https://diablo2.io/uniques/felloak-t767.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'normal',
    code: 'clb',
  },
  {
    id: 'stoutnail',
    name: 'Stoutnail',
    link: 'https://diablo2.io/uniques/stoutnail-t949.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'normal',
    code: 'spc',
  },
  {
    id: 'crushflange',
    name: 'Crushflange',
    link: 'https://diablo2.io/uniques/crushflange-t736.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'normal',
    code: 'mac',
  },
  {
    id: 'bloodrise',
    name: 'Bloodrise',
    link: 'https://diablo2.io/uniques/bloodrise-t705.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'normal',
    code: 'mst',
  },
  {
    id: 'thegeneralstandoliga',
    name: "The General's Tan Do Li Ga",
    link: 'https://diablo2.io/uniques/the-general-s-tan-do-li-ga-t970.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'normal',
    code: 'fla',
  },
  {
    id: 'ironstone',
    name: 'Ironstone',
    link: 'https://diablo2.io/uniques/ironstone-t829.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'normal',
    code: 'whm',
  },
  {
    id: 'darkclancrusher',
    name: 'Dark Clan Crusher',
    link: 'https://diablo2.io/uniques/dark-clan-crusher-t738.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'exceptional',
    code: '9cl',
  },
  {
    id: 'fleshrender',
    name: 'Fleshrender',
    link: 'https://diablo2.io/uniques/fleshrender-t770.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'exceptional',
    code: '9sp',
  },
  {
    id: 'sureshrillfrost',
    name: 'Sureshrill Frost',
    link: 'https://diablo2.io/uniques/sureshrill-frost-t952.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'exceptional',
    code: '9ma',
  },
  {
    id: 'moonfall',
    name: 'Moonfall',
    link: 'https://diablo2.io/uniques/moonfall-t860.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'exceptional',
    code: '9mt',
  },
  {
    id: 'baezilsvortex',
    name: "Baezil's Vortex",
    link: 'https://diablo2.io/uniques/baezil-s-vortex-t682.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'exceptional',
    code: '9fl',
  },
  {
    id: 'earthshaker',
    name: 'Earthshaker',
    link: 'https://diablo2.io/uniques/earthshaker-t762.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'exceptional',
    code: '9wh',
  },
  {
    id: 'nordstenderizer',
    name: "Nord's Tenderizer",
    link: 'https://diablo2.io/uniques/nord-s-tenderizer-t867.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7cl',
  },
  {
    id: 'baranarsstar',
    name: "Baranar's Star",
    link: 'https://diablo2.io/uniques/baranar-s-star-t684.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7mt',
  },
  {
    id: 'demonlimb',
    name: 'Demon Limb',
    link: 'https://diablo2.io/uniques/demon-limb-t747.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7sp',
  },
  {
    id: 'stormlash',
    name: 'Stormlash',
    link: 'https://diablo2.io/uniques/stormlash-t943.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7fl',
  },
  {
    id: 'horizonstornado',
    name: "Horizon's Tornado",
    link: 'https://diablo2.io/uniques/horizon-s-tornado-t820.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7fl',
  },
  {
    id: 'stonecrusher',
    name: 'Stone Crusher',
    link: 'https://diablo2.io/uniques/stone-crusher-t937.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7wh',
  },
  {
    id: 'schaefershammer',
    name: "Schaefer's Hammer",
    link: 'https://diablo2.io/uniques/schaefer-s-hammer-t900.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7wh',
  },
];
