import type { Item } from '../../types/grail';

export const oneHandedClubs: Item[] = [
  {
    id: 'felloak',
    name: 'Felloak',
    link: 'https://diablo2.io/uniques/felloak-t767.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'normal',
    code: 'clb',
    itemBase: 'Club',
    imageFilename: 'felloak.png',
  },
  {
    id: 'stoutnail',
    name: 'Stoutnail',
    link: 'https://diablo2.io/uniques/stoutnail-t949.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'normal',
    code: 'spc',
    itemBase: 'Spiked Club',
    imageFilename: 'stoutnail.png',
  },
  {
    id: 'darkclancrusher',
    name: 'Dark Clan Crusher',
    link: 'https://diablo2.io/uniques/dark-clan-crusher-t738.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'exceptional',
    code: '9cl',
    itemBase: 'Cudgel',
    imageFilename: 'club.png',
  },
  {
    id: 'fleshrender',
    name: 'Fleshrender',
    link: 'https://diablo2.io/uniques/fleshrender-t770.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'exceptional',
    code: '9sp',
    itemBase: 'Barbed Club',
    imageFilename: 'spiked_club.png',
  },
  {
    id: 'nordstenderizer',
    name: "Nord's Tenderizer",
    link: 'https://diablo2.io/uniques/nord-s-tenderizer-t867.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7cl',
    itemBase: 'Truncheon',
    imageFilename: 'club.png',
  },
  {
    id: 'demonlimb',
    name: 'Demon Limb',
    link: 'https://diablo2.io/uniques/demon-limb-t747.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_clubs',
    treasureClass: 'elite',
    code: '7sp',
    itemBase: 'Tyrant Club',
    imageFilename: 'spiked_club.png',
  },
];
