import type { Item } from '../../types/grail';

export const oneHandedSwords: Item[] = [
  {
    id: 'rixotskeen',
    name: "Rixot's Keen",
    link: 'https://diablo2.io/uniques/rixot-s-keen-t892.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'ssd',
    itemBase: 'Short Sword',
    imageFilename: 'short_sword.png',
  },
  {
    id: 'bloodcrescent',
    name: 'Blood Crescent',
    link: 'https://diablo2.io/uniques/blood-crescent-t700.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'scm',
    itemBase: 'Scimitar',
    imageFilename: 'blood_crescent.png',
  },
  {
    id: 'skewerofkrintiz',
    name: 'Skewer of Krintiz',
    link: 'https://diablo2.io/uniques/skewer-of-krintiz-t907.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'sbr',
    itemBase: 'Sabre',
    imageFilename: 'krintizs_skewer.png',
  },
  {
    id: 'gleamscythe',
    name: 'Gleamscythe',
    link: 'https://diablo2.io/uniques/gleamscythe-t782.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'flc',
    itemBase: 'Falchion',
    imageFilename: 'gleamscythe.png',
  },
  {
    id: 'griswoldsedge',
    name: "Griswold's Edge",
    link: 'https://diablo2.io/uniques/griswold-s-edge-t796.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'bsd',
    itemBase: 'Broad Sword',
    imageFilename: 'broad_sword.png',
  },
  {
    id: 'hellplague',
    name: 'Hellplague',
    link: 'https://diablo2.io/uniques/hellplague-t812.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'lsd',
    itemBase: 'Long Sword',
    imageFilename: 'hellplague.png',
  },
  {
    id: 'culwenspoint',
    name: "Culwen's Point",
    link: 'https://diablo2.io/uniques/culwen-s-point-t737.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'normal',
    code: 'wsd',
    itemBase: 'War Sword',
    imageFilename: 'war_sword.png',
  },
  {
    id: 'bloodletter',
    name: 'Bloodletter',
    link: 'https://diablo2.io/uniques/bloodletter-t703.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'exceptional',
    code: '9ss',
    itemBase: 'Falcata',
    imageFilename: 'scimitar.png',
  },
  {
    id: 'coldsteeleye',
    name: 'Coldsteel Eye',
    link: 'https://diablo2.io/uniques/coldsteel-eye-t728.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'exceptional',
    code: '9sm',
    itemBase: 'Ataghan',
    imageFilename: 'saber.png',
  },
  {
    id: 'hexfire',
    name: 'Hexfire',
    link: 'https://diablo2.io/uniques/hexfire-t816.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'exceptional',
    code: '9sb',
    itemBase: 'Scissors Katar',
    imageFilename: 'hexfire.png',
  },
  {
    id: 'bladeofalibaba',
    name: 'Blade of Ali Baba',
    link: 'https://diablo2.io/uniques/blade-of-ali-baba-t695.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'exceptional',
    code: '9fc',
    itemBase: 'Tulwar',
    imageFilename: 'falchion.png',
  },
  {
    id: 'ginthersrift',
    name: "Ginther's Rift",
    link: 'https://diablo2.io/uniques/ginther-s-rift-t781.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'exceptional',
    code: '9cr',
    itemBase: 'Phase Blade',
    imageFilename: 'crystal_sword.png',
  },
  {
    id: 'headstriker',
    name: 'Headstriker',
    link: 'https://diablo2.io/uniques/headstriker-t805.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'exceptional',
    code: '9bs',
    itemBase: 'Gothic Staff',
    imageFilename: 'battle_staff.png',
  },
  {
    id: 'plaguebearer',
    name: 'Plague Bearer',
    link: 'https://diablo2.io/uniques/plague-bearer-t874.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'exceptional',
    code: '9ls',
    itemBase: 'Quarterstaff',
    imageFilename: 'plague_bearer.png',
  },
  {
    id: 'theatlantean',
    name: 'The Atlantean',
    link: 'https://diablo2.io/uniques/the-atlantean-t958.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'exceptional',
    code: '9wd',
    itemBase: 'Mythical Sword',
    imageFilename: 'war_sword.png',
  },
  {
    id: 'azurewrath',
    name: 'Azurewrath',
    link: 'https://diablo2.io/uniques/azurewrath-t681.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'elite',
    code: '7cr',
    itemBase: 'Phase Blade',
    imageFilename: 'crystal_sword.png',
  },
  {
    id: 'bloodmoon',
    name: 'Bloodmoon',
    link: 'https://diablo2.io/uniques/bloodmoon-t704.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'elite',
    code: '7sb',
    itemBase: 'Elegant Blade',
    imageFilename: 'hexfire.png',
  },
  {
    id: 'djinnslayer',
    name: 'Djinn Slayer',
    link: 'https://diablo2.io/uniques/djinn-slayer-t752.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'elite',
    code: '7sm',
    itemBase: 'Mythical Sword',
    imageFilename: 'war_sword.png',
  },
  {
    id: 'frostwind',
    name: 'Frostwind',
    link: 'https://diablo2.io/uniques/frostwind-t773.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'elite',
    code: '7ls',
    itemBase: 'Cryptic Sword',
    imageFilename: 'hellplague.png',
  },
  {
    id: 'lightsabre',
    name: 'Lightsabre',
    link: 'https://diablo2.io/uniques/lightsabre-t847.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '1h_swords',
    treasureClass: 'elite',
    code: '7cr',
    itemBase: 'Phase Blade',
    imageFilename: 'lightsabre.png',
  },
];
