import type { Item } from '../../types/grail';

export const twoHandedAxes: Item[] = [
  {
    id: 'axeoffechmar',
    name: 'Axe of Fechmar',
    link: 'https://diablo2.io/uniques/axe-of-fechmar-t680.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'lax',
  },
  {
    id: 'goreshovel',
    name: 'Goreshovel',
    link: 'https://diablo2.io/uniques/goreshovel-t790.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'bax',
  },
  {
    id: 'thechieftain',
    name: 'The Chieftain',
    link: 'https://diablo2.io/uniques/the-chieftain-t962.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'btx',
  },
  {
    id: 'brainhew',
    name: 'Brainhew',
    link: 'https://diablo2.io/uniques/brainhew-t714.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'gax',
  },
  {
    id: 'humongous',
    name: 'Humongous',
    link: 'https://diablo2.io/uniques/humongous-t823.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'gix',
  },
  {
    id: 'warlordstrust',
    name: "Warlord's Trust",
    link: 'https://diablo2.io/uniques/warlord-s-trust-t1016.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9la',
  },
  {
    id: 'spellsteel',
    name: 'Spellsteel',
    link: 'https://diablo2.io/uniques/spellsteel-t921.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9ba',
  },
  {
    id: 'stormrider',
    name: 'Stormrider',
    link: 'https://diablo2.io/uniques/stormrider-t944.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9bt',
  },
  {
    id: 'boneslayerblade',
    name: 'Boneslayer Blade',
    link: 'https://diablo2.io/uniques/boneslayer-blade-t712.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9ga',
  },
  {
    id: 'theminotaur',
    name: 'The Minotaur',
    link: 'https://diablo2.io/uniques/the-minotaur-t981.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9gi',
  },
  {
    id: 'etherealedge',
    name: 'Ethereal Edge',
    link: 'https://diablo2.io/uniques/ethereal-edge-t765.html',
    etherealType: 'only',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7ba',
  },
  {
    id: 'hellslayer',
    name: 'Hellslayer',
    link: 'https://diablo2.io/uniques/hellslayer-t814.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7bt',
  },
  {
    id: 'messerschmidtsreaver',
    name: "Messerschmidt's Reaver",
    link: 'https://diablo2.io/uniques/messerschmidt-s-reaver-t858.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7ga',
  },
  {
    id: 'executionersjustice',
    name: "Executioner's Justice",
    link: 'https://diablo2.io/uniques/executioner-s-justice-t766.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7gi',
  },
];
