import type { Item } from '../../types/grail';

export const twoHandedAxes: Item[] = [
  {
    id: 'axeoffechmar',
    name: 'Axe of Fechmar',
    link: 'https://diablo2.io/uniques/axe-of-fechmar-t680.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'lax',
    itemBase: 'Large Axe',
  },
  {
    id: 'goreshovel',
    name: 'Goreshovel',
    link: 'https://diablo2.io/uniques/goreshovel-t790.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'bax',
    itemBase: 'Broad Axe',
  },
  {
    id: 'thechieftain',
    name: 'The Chieftain',
    link: 'https://diablo2.io/uniques/the-chieftain-t962.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'btx',
    itemBase: 'Battle Axe',
  },
  {
    id: 'brainhew',
    name: 'Brainhew',
    link: 'https://diablo2.io/uniques/brainhew-t714.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'gax',
    itemBase: 'Great Axe',
  },
  {
    id: 'humongous',
    name: 'Humongous',
    link: 'https://diablo2.io/uniques/humongous-t823.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'normal',
    code: 'gix',
    itemBase: 'Giant Axe',
  },
  {
    id: 'warlordstrust',
    name: "Warlord's Trust",
    link: 'https://diablo2.io/uniques/warlord-s-trust-t1016.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9la',
    itemBase: 'Military Axe',
  },
  {
    id: 'spellsteel',
    name: 'Spellsteel',
    link: 'https://diablo2.io/uniques/spellsteel-t921.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9ba',
    itemBase: 'Hatchet Hands',
  },
  {
    id: 'stormrider',
    name: 'Stormrider',
    link: 'https://diablo2.io/uniques/stormrider-t944.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9bt',
    itemBase: 'Claws',
  },
  {
    id: 'boneslayerblade',
    name: 'Boneslayer Blade',
    link: 'https://diablo2.io/uniques/boneslayer-blade-t712.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9ga',
    itemBase: 'Gothic Axe',
  },
  {
    id: 'theminotaur',
    name: 'The Minotaur',
    link: 'https://diablo2.io/uniques/the-minotaur-t981.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'exceptional',
    code: '9gi',
    itemBase: 'Ancient Axe',
  },
  {
    id: 'etherealedge',
    name: 'Ethereal Edge',
    link: 'https://diablo2.io/uniques/ethereal-edge-t765.html',
    etherealType: 'only',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7ba',
    itemBase: 'Wrist Sword',
  },
  {
    id: 'hellslayer',
    name: 'Hellslayer',
    link: 'https://diablo2.io/uniques/hellslayer-t814.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7bt',
    itemBase: 'Battle Cestus',
  },
  {
    id: 'messerschmidtsreaver',
    name: "Messerschmidt's Reaver",
    link: 'https://diablo2.io/uniques/messerschmidt-s-reaver-t858.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7ga',
    itemBase: 'Champion Axe',
  },
  {
    id: 'executionersjustice',
    name: "Executioner's Justice",
    link: 'https://diablo2.io/uniques/executioner-s-justice-t766.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_axes',
    treasureClass: 'elite',
    code: '7gi',
    itemBase: 'Glorious Axe',
  },
];
