import type { Item } from '../../types/grail';

export const twoHandedClubs: Item[] = [
  {
    id: 'bonesnap',
    name: 'Bonesnap',
    link: 'https://diablo2.io/uniques/bonesnap-t713.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_clubs',
    treasureClass: 'normal',
    code: 'mau',
  },
  {
    id: 'steeldriver',
    name: 'Steeldriver',
    link: 'https://diablo2.io/uniques/steeldriver-t934.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_clubs',
    treasureClass: 'normal',
    code: 'gma',
  },
  {
    id: 'bloodtreestump',
    name: 'Bloodtree Stump',
    link: 'https://diablo2.io/uniques/bloodtree-stump-t707.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_clubs',
    treasureClass: 'exceptional',
    code: '9m9',
  },
  {
    id: 'thegavelofpain',
    name: 'The Gavel of Pain',
    link: 'https://diablo2.io/uniques/the-gavel-of-pain-t969.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_clubs',
    treasureClass: 'exceptional',
    code: '9gm',
  },
  {
    id: 'windhammer',
    name: 'Windhammer',
    link: 'https://diablo2.io/uniques/windhammer-t1022.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_clubs',
    treasureClass: 'elite',
    code: '7m7',
  },
  {
    id: 'earthshifter',
    name: 'Earth Shifter',
    link: 'https://diablo2.io/uniques/earth-shifter-t761.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_clubs',
    treasureClass: 'elite',
    code: '7gm',
  },
  {
    id: 'thecraniumbasher',
    name: 'The Cranium Basher',
    link: 'https://diablo2.io/uniques/the-cranium-basher-t963.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_clubs',
    treasureClass: 'elite',
    code: '7gm',
  },
];
