import type { Item } from '../../types/grail';

export const twoHandedSwords: Item[] = [
  {
    id: 'shadowfang',
    name: 'Shadowfang',
    link: 'https://diablo2.io/uniques/shadowfang-t904.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'normal',
    code: '2hs',
    itemBase: 'Two-Handed Sword',
  },
  {
    id: 'soulflay',
    name: 'Soulflay',
    link: 'https://diablo2.io/uniques/soulflay-t918.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'normal',
    code: 'clm',
    itemBase: 'Claymore',
  },
  {
    id: 'kinemilsawl',
    name: "Kinemil's Awl",
    link: 'https://diablo2.io/uniques/kinemil-s-awl-t834.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'normal',
    code: 'gis',
    itemBase: 'Gladius',
  },
  {
    id: 'blacktongue',
    name: 'Blacktongue',
    link: 'https://diablo2.io/uniques/blacktongue-t694.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'normal',
    code: 'bsw',
    itemBase: 'Bastard Sword',
  },
  {
    id: 'ripsaw',
    name: 'Ripsaw',
    link: 'https://diablo2.io/uniques/ripsaw-t891.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'normal',
    code: 'flb',
    itemBase: 'Flamberge',
  },
  {
    id: 'thepatriarch',
    name: 'The Patriarch',
    link: 'https://diablo2.io/uniques/the-patriarch-t983.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'normal',
    code: 'gsd',
    itemBase: 'Great Sword',
  },
  {
    id: 'craintevomir',
    name: 'Crainte Vomir',
    link: 'https://diablo2.io/uniques/crainte-vomir-t730.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'exceptional',
    code: '92h',
    itemBase: 'Suwayyah',
  },
  {
    id: 'bingszwang',
    name: 'Bing Sz Wang',
    link: 'https://diablo2.io/uniques/bing-sz-wang-t687.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'exceptional',
    code: '9cm',
    itemBase: 'Dacian Falx',
  },
  {
    id: 'thevilehusk',
    name: 'The Vile Husk',
    link: 'https://diablo2.io/uniques/the-vile-husk-t991.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'exceptional',
    code: '9gs',
    itemBase: 'Tusk Sword',
  },
  {
    id: 'cloudcrack',
    name: 'Cloudcrack',
    link: 'https://diablo2.io/uniques/cloudcrack-t725.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'exceptional',
    code: '9b9',
    itemBase: 'Gothic Sword',
  },
  {
    id: 'todesfaelleflamme',
    name: 'Todesfaelle Flamme',
    link: 'https://diablo2.io/uniques/todesfaelle-flamme-t996.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'exceptional',
    code: '9fb',
    itemBase: 'Zweihander',
  },
  {
    id: 'swordguard',
    name: 'Swordguard',
    link: 'https://diablo2.io/uniques/swordguard-t954.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'exceptional',
    code: '9gd',
    itemBase: 'Executioner Sword',
  },
  {
    id: 'flamebellow',
    name: 'Flamebellow',
    link: 'https://diablo2.io/uniques/flamebellow-t769.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'elite',
    code: '7gs',
    itemBase: 'Colossus Blade',
  },
  {
    id: 'doombringer',
    name: 'Doombringer',
    link: 'https://diablo2.io/uniques/doombringer-t753.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'elite',
    code: '7b7',
    itemBase: 'Suwayyah',
  },
  {
    id: 'thegrandfather',
    name: 'The Grandfather',
    link: 'https://diablo2.io/uniques/the-grandfather-t973.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: '2h_swords',
    treasureClass: 'elite',
    code: '7gd',
    itemBase: 'Glorious Axe',
  },
];
