import type { Item } from '../../types/grail';

export const bows: Item[] = [
  {
    id: 'pluckeye',
    name: 'Pluckeye',
    link: 'https://diablo2.io/uniques/pluckeye-t875.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'sbw',
  },
  {
    id: 'witherstring',
    name: 'Witherstring',
    link: 'https://diablo2.io/uniques/witherstring-t1025.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'hbw',
  },
  {
    id: 'ravenclaw',
    name: 'Raven Claw',
    link: 'https://diablo2.io/uniques/raven-claw-t883.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'lbw',
  },
  {
    id: 'roguesbow',
    name: "Rogue's Bow",
    link: 'https://diablo2.io/uniques/rogue-s-bow-t895.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'cbw',
  },
  {
    id: 'stormstrike',
    name: 'Stormstrike',
    link: 'https://diablo2.io/uniques/stormstrike-t948.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'sbb',
  },
  {
    id: 'wizendraw',
    name: 'Wizendraw',
    link: 'https://diablo2.io/uniques/wizendraw-t1027.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'lbb',
  },
  {
    id: 'hellclap',
    name: 'Hellclap',
    link: 'https://diablo2.io/uniques/hellclap-t810.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'swb',
  },
  {
    id: 'blastbark',
    name: 'Blastbark',
    link: 'https://diablo2.io/uniques/blastbark-t698.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'normal',
    code: 'lwb',
  },
  {
    id: 'skystrike',
    name: 'Skystrike',
    link: 'https://diablo2.io/uniques/skystrike-t913.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'exceptional',
    code: '8sb',
  },
  {
    id: 'riphook',
    name: 'Riphook',
    link: 'https://diablo2.io/uniques/riphook-t890.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'exceptional',
    code: '8hb',
  },
  {
    id: 'kukoshakaku',
    name: 'Kuko Shakaku',
    link: 'https://diablo2.io/uniques/kuko-shakaku-t837.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'exceptional',
    code: '8lb',
  },
  {
    id: 'endlesshail',
    name: 'Endlesshail',
    link: 'https://diablo2.io/uniques/endlesshail-t763.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'exceptional',
    code: '8cb',
  },
  {
    id: 'witchwildstring',
    name: 'Witchwild String',
    link: 'https://diablo2.io/uniques/witchwild-string-t1024.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'exceptional',
    code: '8s8',
  },
  {
    id: 'cliffkiller',
    name: 'Cliffkiller',
    link: 'https://diablo2.io/uniques/cliffkiller-t724.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'exceptional',
    code: '8l8',
  },
  {
    id: 'magewrath',
    name: 'Magewrath',
    link: 'https://diablo2.io/uniques/magewrath-t852.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'exceptional',
    code: '8sw',
  },
  {
    id: 'goldstrikearch',
    name: 'Goldstrike Arch',
    link: 'https://diablo2.io/uniques/goldstrike-arch-t786.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'exceptional',
    code: '8lw',
  },
  {
    id: 'widowmaker',
    name: 'Widowmaker',
    link: 'https://diablo2.io/uniques/widowmaker-t1020.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'elite',
    code: '6sw',
  },
  {
    id: 'eaglehorn',
    name: 'Eaglehorn',
    link: 'https://diablo2.io/uniques/eaglehorn-t760.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'elite',
    code: '6l7',
  },
  {
    id: 'windforce',
    name: 'Windforce',
    link: 'https://diablo2.io/uniques/windforce-t1021.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'bows',
    treasureClass: 'elite',
    code: '6lw',
  },
];
