import type { Item } from '../../types/grail';

export const crossbows: Item[] = [
  {
    id: 'leadcrow',
    name: 'Leadcrow',
    link: 'https://diablo2.io/uniques/leadcrow-t843.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'normal',
    code: 'lxb',
    itemBase: 'Light Crossbow',
  },
  {
    id: 'ichorsting',
    name: 'Ichorsting',
    link: 'https://diablo2.io/uniques/ichorsting-t826.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'normal',
    code: 'mxb',
    itemBase: 'Crossbow',
  },
  {
    id: 'hellcast',
    name: 'Hellcast',
    link: 'https://diablo2.io/uniques/hellcast-t809.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'normal',
    code: 'hxb',
    itemBase: 'Heavy Crossbow',
  },
  {
    id: 'doomslinger',
    name: 'Doomslinger',
    link: 'https://diablo2.io/uniques/doomslinger-t754.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'normal',
    code: 'rxb',
    itemBase: 'Repeating Crossbow',
  },
  {
    id: 'langerbriser',
    name: 'Langer Briser',
    link: 'https://diablo2.io/uniques/langer-briser-t841.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'exceptional',
    code: '8lx',
    itemBase: 'Pellet Bow',
  },
  {
    id: 'pusspitter',
    name: 'Pus Spitter',
    link: 'https://diablo2.io/uniques/pus-spitter-t877.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'exceptional',
    code: '8mx',
    itemBase: 'Gorgon Crossbow',
  },
  {
    id: 'burizadokyanon',
    name: 'Buriza-Do Kyanon',
    link: 'https://diablo2.io/uniques/buriza-do-kyanon-t716.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'exceptional',
    code: '8hx',
    itemBase: 'Colossus Crossbow',
  },
  {
    id: 'demonmachine',
    name: 'Demon Machine',
    link: 'https://diablo2.io/uniques/demon-machine-t748.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'exceptional',
    code: '8rx',
    itemBase: 'Demon Crossbow',
  },
  {
    id: 'gutsiphon',
    name: 'Gut Siphon',
    link: 'https://diablo2.io/uniques/gut-siphon-t800.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'elite',
    code: '6rx',
    itemBase: 'Demon Crossbow',
  },
  {
    id: 'hellrack',
    name: 'Hellrack',
    link: 'https://diablo2.io/uniques/hellrack-t813.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'crossbows',
    treasureClass: 'elite',
    code: '6hx',
    itemBase: 'Colossus Crossbow',
  },
];
