import type { Item } from '../../types/grail';

export const daggers: Item[] = [
  {
    id: 'gull',
    name: 'Gull',
    link: 'https://diablo2.io/uniques/gull-t799.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'normal',
    code: 'dgr',
    itemBase: 'Dagger',
    imageFilename: 'dagger.png',
  },
  {
    id: 'thediggler',
    name: 'The Diggler',
    link: 'https://diablo2.io/uniques/the-diggler-t964.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'normal',
    code: 'dir',
    itemBase: 'Dirk',
    imageFilename: 'dirk.png',
  },
  {
    id: 'thejadetando',
    name: 'The Jade Tan Do',
    link: 'https://diablo2.io/uniques/the-jade-tan-do-t978.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'normal',
    code: 'kri',
    itemBase: 'Kris',
    imageFilename: 'the_jade_tan_do.png',
  },
  {
    id: 'spectralshard',
    name: 'Spectral Shard',
    link: 'https://diablo2.io/uniques/spectral-shard-t920.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'normal',
    code: 'bld',
    itemBase: 'Blade',
    imageFilename: 'blade.png',
  },
  {
    id: 'spineripper',
    name: 'Spineripper',
    link: 'https://diablo2.io/uniques/spineripper-t923.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'exceptional',
    code: '9dg',
    itemBase: 'Poignard',
    imageFilename: 'dagger.png',
  },
  {
    id: 'heartcarver',
    name: 'Heart Carver',
    link: 'https://diablo2.io/uniques/heart-carver-t806.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'exceptional',
    code: '9di',
    itemBase: 'Rondel',
    imageFilename: 'dirk.png',
  },
  {
    id: 'blackbogssharp',
    name: "Blackbog's Sharp",
    link: 'https://diablo2.io/uniques/blackbog-s-sharp-t689.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'exceptional',
    code: '9kr',
    itemBase: 'Cinquedeas',
    imageFilename: 'the_jade_tan_do.png',
  },
  {
    id: 'stormspike',
    name: 'Stormspike',
    link: 'https://diablo2.io/uniques/stormspike-t946.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'exceptional',
    code: '9bl',
    itemBase: 'Stiletto',
    imageFilename: 'stormspike.png',
  },
  {
    id: 'fleshripper',
    name: 'Fleshripper',
    link: 'https://diablo2.io/uniques/fleshripper-t771.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'elite',
    code: '7kr',
    itemBase: 'Fanged Knife',
    imageFilename: 'the_jade_tan_do.png',
  },
  {
    id: 'ghostflame',
    name: 'Ghostflame',
    link: 'https://diablo2.io/uniques/ghostflame-t777.html',
    etherealType: 'only',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'elite',
    code: '7bl',
    itemBase: 'Legend Spike',
    imageFilename: 'blade.png',
  },
  {
    id: 'wizardspike',
    name: 'Wizardspike',
    link: 'https://diablo2.io/uniques/wizardspike-t1026.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'daggers',
    treasureClass: 'elite',
    code: '7dg',
    itemBase: 'Bone Knife',
    imageFilename: 'dagger.png',
  },
];
