import type { Item } from '../../types/grail';

export const hammers: Item[] = [
  {
    id: 'ironstone',
    name: 'Ironstone',
    link: 'https://diablo2.io/uniques/ironstone-t829.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'hammers',
    treasureClass: 'normal',
    code: 'whm',
    itemBase: 'War Hammer',
    imageFilename: 'war_hammer.png',
  },
  {
    id: 'earthshaker',
    name: 'Earthshaker',
    link: 'https://diablo2.io/uniques/earthshaker-t762.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'hammers',
    treasureClass: 'exceptional',
    code: '9wh',
    itemBase: 'Battle Hammer',
    imageFilename: 'war_hammer.png',
  },
  {
    id: 'stonecrusher',
    name: 'Stone Crusher',
    link: 'https://diablo2.io/uniques/stone-crusher-t937.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'hammers',
    treasureClass: 'elite',
    code: '7wh',
    itemBase: 'Legendary Mallet',
    imageFilename: 'war_hammer.png',
  },
  {
    id: 'schaefershammer',
    name: "Schaefer's Hammer",
    link: 'https://diablo2.io/uniques/schaefer-s-hammer-t900.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'hammers',
    treasureClass: 'elite',
    code: '7wh',
    itemBase: 'Legendary Mallet',
    imageFilename: 'war_hammer.png',
  },
];
