import type { Item } from '../../types/grail';

export const maces: Item[] = [
  {
    id: 'stormlash',
    name: 'Stormlash',
    link: 'https://diablo2.io/uniques/stormlash-t943.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'elite',
    code: '7fl',
    itemBase: 'Scourge',
    imageFilename: 'flail.png',
  },
  {
    id: 'horizonstornado',
    name: "Horizon's Tornado",
    link: 'https://diablo2.io/uniques/horizon-s-tornado-t820.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'elite',
    code: '7fl',
    itemBase: 'Scourge',
    imageFilename: 'flail.png',
  },
  {
    id: 'sureshrillfrost',
    name: 'Sureshrill Frost',
    link: 'https://diablo2.io/uniques/sureshrill-frost-t952.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'exceptional',
    code: '9ma',
    itemBase: 'Flanged Mace',
    imageFilename: 'mace.png',
  },
  {
    id: 'baranarsstar',
    name: "Baranar's Star",
    link: 'https://diablo2.io/uniques/baranar-s-star-t684.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'elite',
    code: '7mt',
    itemBase: 'Devil Star',
    imageFilename: 'morning_star.png',
  },
  {
    id: 'bloodrise',
    name: 'Bloodrise',
    link: 'https://diablo2.io/uniques/bloodrise-t705.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'normal',
    code: 'mst',
    itemBase: 'Morning Star',
    imageFilename: 'bloodrise.png',
  },
  {
    id: 'moonfall',
    name: 'Moonfall',
    link: 'https://diablo2.io/uniques/moonfall-t860.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'exceptional',
    code: '9mt',
    itemBase: 'Jagged Star',
    imageFilename: 'morning_star.png',
  },
  {
    id: 'baezilsvortex',
    name: "Baezil's Vortex",
    link: 'https://diablo2.io/uniques/baezil-s-vortex-t682.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'exceptional',
    code: '9fl',
    itemBase: 'Knout',
    imageFilename: 'flail.png',
  },

  {
    id: 'crushflange',
    name: 'Crushflange',
    link: 'https://diablo2.io/uniques/crushflange-t736.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'normal',
    code: 'mac',
    itemBase: 'Mace',
    imageFilename: 'mace.png',
  },
  {
    id: 'thegeneralstandoliga',
    name: "The General's Tan Do Li Ga",
    link: 'https://diablo2.io/uniques/the-general-s-tan-do-li-ga-t970.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'maces',
    treasureClass: 'normal',
    code: 'fla',
    itemBase: 'Flail',
    imageFilename: 'flail.png',
  },
];
