import type { Item } from '../../types/grail';

export const mauls: Item[] = [
  {
    id: 'bloodtreestump',
    name: 'Bloodtree Stump',
    link: 'https://diablo2.io/uniques/bloodtree-stump-t707.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'mauls',
    treasureClass: 'exceptional',
    code: '9m9',
    itemBase: 'War Club',
    imageFilename: 'maul.png',
  },
  {
    id: 'thecraniumbasher',
    name: 'The Cranium Basher',
    link: 'https://diablo2.io/uniques/the-cranium-basher-t963.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'mauls',
    treasureClass: 'elite',
    code: '7gm',
    itemBase: 'Thunder Maul',
    imageFilename: 'great_maul.png',
  },
  {
    id: 'thegavelofpain',
    name: 'The Gavel of Pain',
    link: 'https://diablo2.io/uniques/the-gavel-of-pain-t969.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'mauls',
    treasureClass: 'exceptional',
    code: '9gm',
    itemBase: 'Martel de Fer',
    imageFilename: 'the_gavel_of_pain.png',
  },
  {
    id: 'earthshifter',
    name: 'Earth Shifter',
    link: 'https://diablo2.io/uniques/earth-shifter-t761.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'mauls',
    treasureClass: 'elite',
    code: '7gm',
    itemBase: 'Thunder Maul',
    imageFilename: 'great_maul.png',
  },
  {
    id: 'bonesnap',
    name: 'Bonesnap',
    link: 'https://diablo2.io/uniques/bonesnap-t713.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'mauls',
    treasureClass: 'normal',
    code: 'mau',
    itemBase: 'Maul',
    imageFilename: 'maul.png',
  },
  {
    id: 'steeldriver',
    name: 'Steeldriver',
    link: 'https://diablo2.io/uniques/steeldriver-t934.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'mauls',
    treasureClass: 'normal',
    code: 'gma',
    itemBase: 'Great Maul',
    imageFilename: 'great_maul.png',
  },
  {
    id: 'windhammer',
    name: 'Windhammer',
    link: 'https://diablo2.io/uniques/windhammer-t1022.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'mauls',
    treasureClass: 'elite',
    code: '7m7',
    itemBase: 'Ogre Maul',
    imageFilename: 'maul.png',
  },
];
