import type { Item } from '../../types/grail';

export const polearms: Item[] = [
  {
    id: 'dimoakshew',
    name: "Dimoak's Hew",
    link: 'https://diablo2.io/uniques/dimoak-s-hew-t751.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'normal',
    code: 'bar',
    itemBase: 'Bardiche',
    imageFilename: 'bardiche.png',
  },
  {
    id: 'steelgoad',
    name: 'Steelgoad',
    link: 'https://diablo2.io/uniques/steelgoad-t935.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'normal',
    code: 'vou',
    itemBase: 'Voulge',
    imageFilename: 'voulge.png',
  },
  {
    id: 'soulharvest',
    name: 'Soul Harvest',
    link: 'https://diablo2.io/uniques/soul-harvest-t36.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'normal',
    code: 'scy',
    itemBase: 'Scythe',
    imageFilename: 'soul_harvest.png',
  },
  {
    id: 'thebattlebranch',
    name: 'The Battlebranch',
    link: 'https://diablo2.io/uniques/the-battlebranch-t959.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'normal',
    code: 'pax',
    itemBase: 'Poleaxe',
    imageFilename: 'poleaxe.png',
  },
  {
    id: 'woestave',
    name: 'Woestave',
    link: 'https://diablo2.io/uniques/woestave-t1028.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'normal',
    code: 'hal',
    itemBase: 'Halberd',
    imageFilename: 'halberd.png',
  },
  {
    id: 'thegrimreaper',
    name: 'The Grim Reaper',
    link: 'https://diablo2.io/uniques/the-grim-reaper-t974.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'normal',
    code: 'wsc',
    itemBase: 'War Scythe',
    imageFilename: 'war_scythe.png',
  },
  {
    id: 'themeatscraper',
    name: 'The Meat Scraper',
    link: 'https://diablo2.io/uniques/the-meat-scraper-t980.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'exceptional',
    code: '9b7',
    itemBase: 'Edge Bow',
    imageFilename: 'short_bow.png',
  },
  {
    id: 'blackleachblade',
    name: 'Blackleach Blade',
    link: 'https://diablo2.io/uniques/blackleach-blade-t692.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'exceptional',
    code: '9vo',
    itemBase: 'Bill',
    imageFilename: 'voulge.png',
  },
  {
    id: 'athenaswrath',
    name: "Athena's Wrath",
    link: 'https://diablo2.io/uniques/athena-s-wrath-t677.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'exceptional',
    code: '9s8',
    itemBase: 'Short Siege Bow',
    imageFilename: 'short_battle_bow.png',
  },
  {
    id: 'pierretombalecouant',
    name: 'Pierre Tombale Couant',
    link: 'https://diablo2.io/uniques/pierre-tombale-couant-t873.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'exceptional',
    code: '9pa',
    itemBase: 'Partizan',
    imageFilename: 'poleaxe.png',
  },
  {
    id: 'husoldalevo',
    name: 'Husoldal Evo',
    link: 'https://diablo2.io/uniques/husoldal-evo-t824.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'exceptional',
    code: '9h9',
    itemBase: 'Bec-De-Corbin',
    imageFilename: 'halberd.png',
  },
  {
    id: 'grimsburningdead',
    name: "Grim's Burning Dead",
    link: 'https://diablo2.io/uniques/grim-s-burning-dead-t795.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'exceptional',
    code: '9wc',
    itemBase: 'Grim Scythe',
    imageFilename: 'war_scythe.png',
  },
  {
    id: 'bonehew',
    name: 'Bonehew',
    link: 'https://diablo2.io/uniques/bonehew-t710.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'elite',
    code: '7o7',
    itemBase: 'Ogre Axe',
    imageFilename: 'bardiche.png',
  },
  {
    id: 'thereaperstoll',
    name: "The Reaper's Toll",
    link: 'https://diablo2.io/uniques/the-reaper-s-toll-t984.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'elite',
    code: '7s8',
    itemBase: 'Thresher',
    imageFilename: 'scythe.png',
  },
  {
    id: 'tombreaver',
    name: 'Tomb Reaver',
    link: 'https://diablo2.io/uniques/tomb-reaver-t997.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'elite',
    code: '7pa',
    itemBase: 'Cryptic Axe',
    imageFilename: 'poleaxe.png',
  },
  {
    id: 'stormspire',
    name: 'Stormspire',
    link: 'https://diablo2.io/uniques/stormspire-t947.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'polearms',
    treasureClass: 'elite',
    code: '7wc',
    itemBase: 'Giant Thresher',
    imageFilename: 'war_scythe.png',
  },
];
