import type { Item } from '../../types/grail';

export const scepters: Item[] = [
  {
    id: 'knellstriker',
    name: 'Knell Striker',
    link: 'https://diablo2.io/uniques/knell-striker-t836.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'normal',
    code: 'scp',
    itemBase: 'Scepter',
  },
  {
    id: 'rusthandle',
    name: 'Rusthandle',
    link: 'https://diablo2.io/uniques/rusthandle-t897.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'normal',
    code: 'gsc',
    itemBase: 'Grand Scepter',
  },
  {
    id: 'stormeye',
    name: 'Stormeye',
    link: 'https://diablo2.io/uniques/stormeye-t941.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'normal',
    code: 'wsp',
    itemBase: 'War Scepter',
  },
  {
    id: 'zakarumshand',
    name: "Zakarum's Hand",
    link: 'https://diablo2.io/uniques/zakarum-s-hand-t1032.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'exceptional',
    code: '9sc',
    itemBase: 'Blade Talons',
  },
  {
    id: 'thefetidsprinkler',
    name: 'The Fetid Sprinkler',
    link: 'https://diablo2.io/uniques/the-fetid-sprinkler-t968.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'exceptional',
    code: '9qs',
    itemBase: 'Holy Water Sprinkler',
  },
  {
    id: 'handofblessedlight',
    name: 'Hand of Blessed Light',
    link: 'https://diablo2.io/uniques/hand-of-blessed-light-t802.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'exceptional',
    code: '9ws',
    itemBase: 'Divine Scepter',
  },
  {
    id: 'astreonsironward',
    name: "Astreon's Iron Ward",
    link: 'https://diablo2.io/uniques/astreon-s-iron-ward-t676.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'elite',
    code: '7ws',
    itemBase: 'Caduceus',
  },
  {
    id: 'heavenslight',
    name: "Heaven's Light",
    link: 'https://diablo2.io/uniques/heaven-s-light-t808.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'elite',
    code: '7sc',
    itemBase: 'Feral Claws',
  },
  {
    id: 'theredeemer',
    name: 'The Redeemer',
    link: 'https://diablo2.io/uniques/the-redeemer-t985.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'scepters',
    treasureClass: 'elite',
    code: '7sc',
    itemBase: 'Feral Claws',
  },
];
