import type { Item } from '../../types/grail';

export const spears: Item[] = [
  {
    id: 'thedragonchang',
    name: 'The Dragon Chang',
    link: 'https://diablo2.io/uniques/the-dragon-chang-t965.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'normal',
    code: 'spr',
    itemBase: 'Spear',
    imageFilename: 'spear.png',
  },
  {
    id: 'razortine',
    name: 'Razortine',
    link: 'https://diablo2.io/uniques/razortine-t888.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'normal',
    code: 'tri',
    itemBase: 'Trident',
    imageFilename: 'razortine.png',
  },
  {
    id: 'bloodthief',
    name: 'Bloodthief',
    link: 'https://diablo2.io/uniques/bloodthief-t706.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'normal',
    code: 'brn',
    itemBase: 'Brandistock',
    imageFilename: 'brandistock.png',
  },
  {
    id: 'lanceofyaggai',
    name: 'Lance of Yaggai',
    link: 'https://diablo2.io/uniques/lance-of-yaggai-t840.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'normal',
    code: 'spt',
    itemBase: 'Spetum',
    imageFilename: 'spetum.png',
  },
  {
    id: 'thetannrgorerod',
    name: 'The Tannr Gorerod',
    link: 'https://diablo2.io/uniques/the-tannr-gorerod-t990.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'normal',
    code: 'pik',
    itemBase: 'Pike',
    imageFilename: 'pike.png',
  },
  {
    id: 'theimpaler',
    name: 'The Impaler',
    link: 'https://diablo2.io/uniques/the-impaler-t976.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'exceptional',
    code: '9sr',
    itemBase: 'War Spear',
    imageFilename: 'spear.png',
  },
  {
    id: 'kelpiesnare',
    name: 'Kelpie Snare',
    link: 'https://diablo2.io/uniques/kelpie-snare-t833.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'exceptional',
    code: '9tr',
    itemBase: 'Fuscina',
    imageFilename: 'razortine.png',
  },
  {
    id: 'soulfeasttine',
    name: 'Soulfeast Tine',
    link: 'https://diablo2.io/uniques/soulfeast-tine-t917.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'exceptional',
    code: '9br',
    itemBase: 'War Fork',
    imageFilename: 'soulfeast_tine.png',
  },
  {
    id: 'honesundan',
    name: 'Hone Sundan',
    link: 'https://diablo2.io/uniques/hone-sundan-t819.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'exceptional',
    code: '9st',
    itemBase: 'Yari',
    imageFilename: 'brandistock.png',
  },
  {
    id: 'spireofhonor',
    name: 'Spire of Honor',
    link: 'https://diablo2.io/uniques/spire-of-honor-t924.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'exceptional',
    code: '9p9',
    itemBase: 'Lance',
    imageFilename: 'pike.png',
  },
  {
    id: 'ariocsneedle',
    name: "Arioc's Needle",
    link: 'https://diablo2.io/uniques/arioc-s-needle-t672.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'elite',
    code: '7sr',
    itemBase: 'Hyperion Spear',
    imageFilename: 'spear.png',
  },
  {
    id: 'steelpillar',
    name: 'Steel Pillar',
    link: 'https://diablo2.io/uniques/steel-pillar-t931.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'elite',
    code: '7p7',
    itemBase: 'War Pike',
    imageFilename: 'pike.png',
  },
  {
    id: 'viperfork',
    name: 'Viperfork',
    link: 'https://diablo2.io/uniques/viperfork-t1012.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'spears',
    treasureClass: 'elite',
    code: '7br',
    itemBase: 'War Fist',
    imageFilename: 'hatchet_hands.png',
  },
];
