import type { Item } from '../../types/grail';

export const staves: Item[] = [
  {
    id: 'baneash',
    name: 'Bane Ash',
    link: 'https://diablo2.io/uniques/bane-ash-t683.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'normal',
    code: 'sst',
  },
  {
    id: 'serpentlord',
    name: 'Serpent Lord',
    link: 'https://diablo2.io/uniques/serpent-lord-t901.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'normal',
    code: 'lst',
  },
  {
    id: 'spireoflazarus',
    name: 'Spire of Lazarus',
    link: 'https://diablo2.io/uniques/spire-of-lazarus-t925.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'normal',
    code: 'cst',
  },
  {
    id: 'thesalamander',
    name: 'The Salamander',
    link: 'https://diablo2.io/uniques/the-salamander-t987.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'normal',
    code: 'bst',
  },
  {
    id: 'theironjangbong',
    name: 'The Iron Jang Bong',
    link: 'https://diablo2.io/uniques/the-iron-jang-bong-t977.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'normal',
    code: 'wst',
  },
  {
    id: 'razorswitch',
    name: 'Razorswitch',
    link: 'https://diablo2.io/uniques/razorswitch-t257.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'exceptional',
    code: '8ss',
  },
  {
    id: 'ribcracker',
    name: 'Ribcracker',
    link: 'https://diablo2.io/uniques/ribcracker-t889.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'exceptional',
    code: '8ls',
  },
  {
    id: 'chromaticire',
    name: 'Chromatic Ire',
    link: 'https://diablo2.io/uniques/chromatic-ire-t723.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'exceptional',
    code: '8cs',
  },
  {
    id: 'warpspear',
    name: 'Warpspear',
    link: 'https://diablo2.io/uniques/warpspear-t1017.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'exceptional',
    code: '8bs',
  },
  {
    id: 'skullcollector',
    name: 'Skull Collector',
    link: 'https://diablo2.io/uniques/skull-collector-t910.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'exceptional',
    code: '8ws',
  },
  {
    id: 'mangsongslesson',
    name: "Mang Song's Lesson",
    link: 'https://diablo2.io/uniques/mang-song-s-lesson-t854.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'elite',
    code: '6ws',
  },
  {
    id: 'ondalswisdom',
    name: "Ondal's Wisdom",
    link: 'https://diablo2.io/uniques/ondal-s-wisdom-t869.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'staves',
    treasureClass: 'elite',
    code: '6cs',
  },
];
