import type { Item } from '../../types/grail';

export const throwing: Item[] = [
  {
    id: 'deathbit',
    name: 'Deathbit',
    link: 'https://diablo2.io/uniques/deathbit-t743.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'exceptional',
    code: '9tk',
    itemBase: 'Battle Dart',
    imageFilename: 'throwing_knife.png',
  },
  {
    id: 'thescalper',
    name: 'The Scalper',
    link: 'https://diablo2.io/uniques/the-scalper-t988.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'exceptional',
    code: '9ta',
    itemBase: 'Francisca',
    imageFilename: 'throwing_axe.png',
  },
  {
    id: 'gimmershred',
    name: 'Gimmershred',
    link: 'https://diablo2.io/uniques/gimmershred-t780.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7ta',
    itemBase: 'Tomahawk',
    imageFilename: 'throwing_axe.png',
  },
  {
    id: 'lacerator',
    name: 'Lacerator',
    link: 'https://diablo2.io/uniques/lacerator-t838.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7b8',
    itemBase: 'Winged Axe',
    imageFilename: 'balanced_axe.png',
  },
  {
    id: 'warshrike',
    name: 'Warshrike',
    link: 'https://diablo2.io/uniques/warshrike-t1018.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7bk',
    itemBase: 'Winged Knife',
    imageFilename: 'warshrike.png',
  },
];
