import type { Item } from '../../types/grail';

export const throwing: Item[] = [
  {
    id: 'deathbit',
    name: 'Deathbit',
    link: 'https://diablo2.io/uniques/deathbit-t743.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'exceptional',
    code: '9tk',
    itemBase: 'Francisca',
  },
  {
    id: 'thescalper',
    name: 'The Scalper',
    link: 'https://diablo2.io/uniques/the-scalper-t988.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'exceptional',
    code: '9ta',
    itemBase: 'Francisca',
  },
  {
    id: 'gimmershred',
    name: 'Gimmershred',
    link: 'https://diablo2.io/uniques/gimmershred-t780.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7ta',
    itemBase: 'Tomahawk',
  },
  {
    id: 'lacerator',
    name: 'Lacerator',
    link: 'https://diablo2.io/uniques/lacerator-t838.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7b8',
    itemBase: 'Wrist Sword',
  },
  {
    id: 'warshrike',
    name: 'Warshrike',
    link: 'https://diablo2.io/uniques/warshrike-t1018.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7bk',
    itemBase: 'Winged Knife',
  },
  {
    id: 'demonsarch',
    name: "Demon's Arch",
    link: 'https://diablo2.io/uniques/demon-s-arch-t750.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7s7',
    itemBase: 'Balrog Spear',
  },
  {
    id: 'wraithflight',
    name: 'Wraith Flight',
    link: 'https://diablo2.io/uniques/wraith-flight-t1031.html',
    etherealType: 'only',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7gl',
    itemBase: 'Ghost Glaive',
  },
  {
    id: 'gargoylesbite',
    name: "Gargoyle's Bite",
    link: 'https://diablo2.io/uniques/gargoyle-s-bite-t774.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'throwing',
    treasureClass: 'elite',
    code: '7ts',
    itemBase: 'Winged Harpoon',
  },
];
