import type { Item } from '../../types/grail';

export const wands: Item[] = [
  {
    id: 'torchofiro',
    name: 'Torch of Iro',
    link: 'https://diablo2.io/uniques/torch-of-iro-t999.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'normal',
    code: 'wnd',
  },
  {
    id: 'maelstrom',
    name: 'Maelstrom',
    link: 'https://diablo2.io/uniques/maelstrom-t850.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'normal',
    code: 'ywn',
  },
  {
    id: 'gravenspine',
    name: 'Gravenspine',
    link: 'https://diablo2.io/uniques/gravenspine-t791.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'normal',
    code: 'bwn',
  },
  {
    id: 'umeslament',
    name: "Ume's Lament",
    link: 'https://diablo2.io/uniques/ume-s-lament-t1004.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'normal',
    code: 'gwn',
  },
  {
    id: 'suicidebranch',
    name: 'Suicide Branch',
    link: 'https://diablo2.io/uniques/suicide-branch-t951.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'exceptional',
    code: '9wn',
  },
  {
    id: 'carinshard',
    name: 'Carin Shard',
    link: 'https://diablo2.io/uniques/carin-shard-t719.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'exceptional',
    code: '9yw',
  },
  {
    id: 'armofkingleoric',
    name: 'Arm of King Leoric',
    link: 'https://diablo2.io/uniques/arm-of-king-leoric-t674.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'exceptional',
    code: '9bw',
  },
  {
    id: 'blackhandkey',
    name: 'Blackhand Key',
    link: 'https://diablo2.io/uniques/blackhand-key-t690.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'exceptional',
    code: '9gw',
  },
  {
    id: 'boneshade',
    name: 'Boneshade',
    link: 'https://diablo2.io/uniques/boneshade-t711.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'elite',
    code: '7bw',
  },
  {
    id: 'deathsweb',
    name: "Death's Web",
    link: 'https://diablo2.io/uniques/death-s-web-t745.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'wands',
    treasureClass: 'elite',
    code: '7gw',
  },
];
