import type { Item } from '../../types/grail';

export const amazon: Item[] = [
  {
    id: 'lycandersaim',
    name: "Lycander's Aim",
    link: 'https://diablo2.io/uniques/lycander-s-aim-t848.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'amazon',
    treasureClass: 'exceptional',
    code: 'am7',
    itemBase: 'Stag Bow',
    imageFilename: 'reflex_bow.png',
  },
  {
    id: 'titansrevenge',
    name: "Titan's Revenge",
    link: 'https://diablo2.io/uniques/titan-s-revenge-t995.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'amazon',
    treasureClass: 'exceptional',
    code: 'ama',
    itemBase: 'Ceremonial Javelin',
    imageFilename: 'maiden_javelin.png',
  },
  {
    id: 'lycandersflank',
    name: "Lycander's Flank",
    link: 'https://diablo2.io/uniques/lycander-s-flank-t849.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'amazon',
    treasureClass: 'exceptional',
    code: 'am9',
    itemBase: 'Ceremonial Pike',
    imageFilename: 'maiden_pike.png',
  },
  {
    id: 'bloodravenscharge',
    name: "Blood Raven's Charge",
    link: 'https://diablo2.io/uniques/blood-raven-s-charge-t701.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'amazon',
    treasureClass: 'elite',
    code: 'amb',
    itemBase: 'Matriarchal Bow',
    imageFilename: 'hellclap.png',
  },
  {
    id: 'thunderstroke',
    name: 'Thunderstroke',
    link: 'https://diablo2.io/uniques/thunderstroke-t993.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'amazon',
    treasureClass: 'elite',
    code: 'amf',
    itemBase: 'Matriarchal Javelin',
    imageFilename: 'maiden_javelin.png',
  },
  {
    id: 'stoneraven',
    name: 'Stoneraven',
    link: 'https://diablo2.io/uniques/stoneraven-t939.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'weapons',
    subCategory: 'amazon',
    treasureClass: 'elite',
    code: 'amd',
    itemBase: 'Matriarchal Spear',
    imageFilename: 'maiden_spear.png',
  },
];
