import type { Item } from '../../types/grail';

export const necromancer: Item[] = [
  {
    id: 'homunculus',
    name: 'Homunculus',
    link: 'https://diablo2.io/uniques/homunculus-t818.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'necromancer',
    treasureClass: 'exceptional',
    code: 'nea',
    itemBase: 'Hierophant Mask',
    imageFilename: 'demon_head.png',
  },
  {
    id: 'boneflame',
    name: 'Boneflame',
    link: 'https://diablo2.io/uniques/boneflame-t708.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'necromancer',
    treasureClass: 'elite',
    code: 'nee',
    itemBase: 'Succubus Skill',
    imageFilename: 'gargoyle_head.png',
  },
  {
    id: 'darkforcespawn',
    name: 'Darkforce Spawn',
    link: 'https://diablo2.io/uniques/darkforce-spawn-t739.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'armor',
    subCategory: 'necromancer',
    treasureClass: 'elite',
    code: 'nef',
    itemBase: 'Bloodlord Skull',
    imageFilename: 'demon_head.png',
  },
];
