import type { Item } from '../../types/grail';

export const amulets: Item[] = [
  {
    id: 'nokozanrelic',
    name: 'Nokozan Relic',
    link: 'https://diablo2.io/uniques/nokozan-relic-t866.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'theeyeofetlich',
    name: 'The Eye of Etlich',
    link: 'https://diablo2.io/uniques/the-eye-of-etlich-t966.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'themahimoakcurio',
    name: 'The Mahim-Oak Curio',
    link: 'https://diablo2.io/uniques/the-mahim-oak-curio-t979.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'saracenschance',
    name: "Saracen's Chance",
    link: 'https://diablo2.io/uniques/saracen-s-chance-t899.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'thecatseye',
    name: "The Cat's Eye",
    link: 'https://diablo2.io/uniques/the-cat-s-eye-t960.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'therisingsun',
    name: 'The Rising Sun',
    link: 'https://diablo2.io/uniques/the-rising-sun-t986.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'crescentmoon-amulet',
    name: 'Crescent Moon',
    link: 'https://diablo2.io/uniques/crescent-moon-amulet-t732.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'atmasscarab',
    name: "Atma's Scarab",
    link: 'https://diablo2.io/uniques/atma-s-scarab-t678.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'highlordswrath',
    name: "Highlord's Wrath",
    link: 'https://diablo2.io/uniques/highlord-s-wrath-t817.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'maraskaleidoscope',
    name: "Mara's Kaleidoscope",
    link: 'https://diablo2.io/uniques/mara-s-kaleidoscope-t855.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'seraphshymn',
    name: "Seraph's Hymn",
    link: 'https://diablo2.io/uniques/seraph-s-hymn-t41.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
  {
    id: 'metalgrid',
    name: 'Metalgrid',
    link: 'https://diablo2.io/uniques/metalgrid-t859.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'amulets',
    code: 'amu',
    itemBase: 'Amulet',
    treasureClass: 'normal',
  },
];
