import type { Item } from '../../types/grail';

export const charms: Item[] = [
  {
    id: 'annihilus',
    code: 'cm1',
    itemBase: 'Small Charm',
    name: 'Annihilus',
    link: 'https://diablo2.io/uniques/annihilus-t670.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'small_charms',
    treasureClass: 'normal',
    imageFilename: 'mephisto_soul_stone.png',
  },
  {
    id: 'gheedsfortune',
    code: 'cm3',
    itemBase: 'Grand Charm',
    name: "Gheed's Fortune",
    link: 'https://diablo2.io/uniques/gheed-s-fortune-t776.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'grand_charms',
    treasureClass: 'normal',
    imageFilename: 'charm_large3.png',
  },
  {
    id: 'hellfiretorch',
    code: 'cm2',
    itemBase: 'Large Charm',
    name: 'Hellfire Torch',
    link: 'https://diablo2.io/uniques/hellfire-torch-t39.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'large_charms',
    treasureClass: 'normal',
    imageFilename: 'torch.png',
  },
];
