import type { Item } from '../../types/grail';

export const charms: Item[] = [
  {
    id: 'annihilus',
    code: 'cm1',
    itemBase: 'Small Charm',
    name: 'Annihilus',
    link: 'https://diablo2.io/uniques/annihilus-t670.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'small_charms',
    treasureClass: 'normal',
    imageFilename: 'mephisto_soul_stone.png',
  },
  {
    id: 'gheedsfortune',
    code: 'cm3',
    itemBase: 'Grand Charm',
    name: "Gheed's Fortune",
    link: 'https://diablo2.io/uniques/gheed-s-fortune-t776.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'grand_charms',
    treasureClass: 'normal',
    imageFilename: 'charm_large3.png',
  },
  {
    id: 'hellfiretorch',
    code: 'cm2',
    itemBase: 'Large Charm',
    name: 'Hellfire Torch',
    link: 'https://diablo2.io/uniques/hellfire-torch-t39.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'large_charms',
    treasureClass: 'normal',
    imageFilename: 'torch.png',
  },
  {
    id: 'bonebreak',
    name: 'Bone Break',
    link: 'https://diablo2.io/uniques/bone-break-t1135126.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'grand_charms',
    treasureClass: 'normal',
    imageFilename: 'charm_large.png',
  },
  {
    id: 'blackcleft',
    name: 'Black Cleft',
    link: 'https://diablo2.io/uniques/black-cleft-t1135125.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'grand_charms',
    treasureClass: 'normal',
    imageFilename: 'charm_large1.png',
  },
  {
    id: 'coldrupture',
    name: 'Cold Rupture',
    link: 'https://diablo2.io/uniques/cold-rupture-t1135124.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'grand_charms',
    treasureClass: 'normal',
    imageFilename: 'charm_large2.png',
  },
  {
    id: 'crackoftheheavens',
    name: 'Crack of the Heavens',
    link: 'https://diablo2.io/uniques/crack-of-the-heavens-t1135127.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'grand_charms',
    treasureClass: 'normal',
    imageFilename: 'charm_large3.png',
  },
  {
    id: 'rottingfissure',
    name: 'Rotting Fissure',
    link: 'https://diablo2.io/uniques/rotting-fissure-t1135129.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'grand_charms',
    treasureClass: 'normal',
    imageFilename: 'charm_large.png',
  },
  {
    id: 'flamerift',
    name: 'Flame Rift',
    link: 'https://diablo2.io/uniques/flame-rift-t1135128.html',
    etherealType: 'none',
    type: 'unique',
    category: 'charms',
    subCategory: 'grand_charms',
    treasureClass: 'normal',
    imageFilename: 'charm_large1.png',
  },
];
