import type { Item } from 'electron/types/grail';

export const jewels: Item[] = [
  {
    id: 'rainbowfacetcoldlevelup',
    code: 'jew',
    itemBase: 'Jewel',
    name: 'Rainbow Facet: Cold Level-up',
    link: 'https://diablo2.io/uniques/rainbow-facet-cold-level-up-t3168.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rainbow_facets',
    treasureClass: 'normal',
    imageFilename: 'perfect_diamond2.png',
  },
  {
    id: 'rainbowfacetfirelevelup',
    code: 'jew',
    itemBase: 'Jewel',
    name: 'Rainbow Facet: Fire Level-up',
    link: 'https://diablo2.io/uniques/rainbow-facet-fire-level-up-t3160.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rainbow_facets',
    treasureClass: 'normal',
    imageFilename: 'perfect_diamond5.png',
  },
  {
    id: 'rainbowfacetlightninglevelup',
    code: 'jew',
    itemBase: 'Jewel',
    name: 'Rainbow Facet: Lightning Level-up',
    link: '',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rainbow_facets',
    treasureClass: 'normal',
    imageFilename: 'perfect_diamond6.png',
  },
  {
    id: 'rainbowfacetpoisonlevelup',
    code: 'jew',
    itemBase: 'Jewel',
    name: 'Rainbow Facet: Poison Level-up',
    link: 'https://diablo2.io/uniques/rainbow-facet-poison-level-up-t3164.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rainbow_facets',
    treasureClass: 'normal',
    imageFilename: 'perfect_diamond4.png',
  },
  {
    id: 'rainbowfacetcolddeath',
    code: 'jew',
    itemBase: 'Jewel',
    name: 'Rainbow Facet: Cold Death',
    link: 'https://diablo2.io/uniques/rainbow-facet-cold-death-t3169.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'dies',
    treasureClass: 'normal',
    imageFilename: 'perfect_diamond2.png',
  },
  {
    id: 'rainbowfacetfiredeath',
    code: 'jew',
    itemBase: 'Jewel',
    name: 'Rainbow Facet: Fire Death',
    link: 'https://diablo2.io/uniques/rainbow-facet-fire-death-t3162.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'dies',
    treasureClass: 'normal',
    imageFilename: 'perfect_diamond5.png',
  },
  {
    id: 'rainbowfacetlightningdeath',
    code: 'jew',
    itemBase: 'Jewel',
    name: 'Rainbow Facet: Lightning Death',
    link: 'https://diablo2.io/uniques/rainbow-facet-lightning-death-t3167.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'dies',
    treasureClass: 'normal',
    imageFilename: 'perfect_diamond6.png',
  },
  {
    id: 'rainbowfacetpoisondeath',
    code: 'jew',
    itemBase: 'Jewel',
    name: 'Rainbow Facet: Poison Death',
    link: 'https://diablo2.io/uniques/rainbow-facet-poison-death-t3165.html',
    etherealType: 'none',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'dies',
    treasureClass: 'normal',
    imageFilename: 'perfect_diamond4.png',
  },
];
