import type { Item } from '../../types/grail';

export const rings: Item[] = [
  {
    id: 'nagelring',
    name: 'Nagelring',
    link: 'https://diablo2.io/uniques/nagelring-t862.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
  {
    id: 'manaldheal',
    name: 'Manald Heal',
    link: 'https://diablo2.io/uniques/manald-heal-t853.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
  {
    id: 'thestoneofjordan',
    name: 'The Stone of Jordan',
    link: 'https://diablo2.io/uniques/stone-of-jordan-t938.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
  {
    id: 'dwarfstar',
    name: 'Dwarf Star',
    link: 'https://diablo2.io/uniques/dwarf-star-t759.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
  {
    id: 'ravenfrost',
    name: 'Raven Frost',
    link: 'https://diablo2.io/uniques/raven-frost-t884.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
  {
    id: 'bulkathosweddingband',
    name: "Bul-Kathos' Wedding Band",
    link: 'https://diablo2.io/uniques/bul-kathos-wedding-band-t715.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
  {
    id: 'carrionwind',
    name: 'Carrion Wind',
    link: 'https://diablo2.io/uniques/carrion-wind-t720.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
  {
    id: 'naturespeace',
    name: "Nature's Peace",
    link: 'https://diablo2.io/uniques/nature-s-peace-t863.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
  {
    id: 'wispprojector',
    name: 'Wisp Projector',
    link: 'https://diablo2.io/uniques/wisp-projector-t1023.html',
    etherealType: 'optional',
    type: 'unique',
    category: 'jewelry',
    subCategory: 'rings',
    code: 'rin',
    treasureClass: 'normal',
  },
];
